#!/usr/bin/env python3
"""Regenerate tests/fixtures/wire-shape-baseline.json from a specs
directory: the committed snapshot, tests/fixtures/openapi (see its
README), or a checkout of the platform's docs/api.

Usage:
    python3 scripts/wire_shape/refresh.py <specs_dir> [--sha <SHA>]

For the snapshot, the pinned commit is the one its generated headers
name, and a --sha that disagrees with them is refused. A directory
without those headers (a platform checkout) needs --sha. There is no
fallback to `git rev-parse HEAD`: inside this repository that names
the SDK's own commit, which would pin the baseline to a revision the
specs never had. Without a commit the script exits non-zero rather
than write a baseline with an empty openapi_specs_sha (the next CI
run would fail at bootstrap).

The baseline is written atomically (temp-file + rename) so a
mid-encode crash can't leave a truncated file behind.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib import (  # noqa: E402
    BASELINE_PATH,
    REPO_ROOT,
    difference,
    discover_sdk_types,
    load_all_schemas,
    snapshot_source_commit,
    write_baseline,
)


def _pinned_sha(specs_dir: Path, explicit_sha: str | None) -> str:
    """Return the platform commit to pin, or "" after saying why there is none."""
    header_sha = snapshot_source_commit(specs_dir)
    if header_sha is None:
        sha = (explicit_sha or "").strip()
        if not sha:
            print(
                f"error: {specs_dir} is not a generated snapshot (no file carries\n"
                "  the header naming its platform commit), so pass --sha <commit-sha>\n"
                "  for the platform checkout it came from. An empty SHA would poison\n"
                "  tests/fixtures/wire-shape-baseline.json and break the next CI\n"
                "  wire-shape-contract run at bootstrap.",
                file=sys.stderr,
            )
        return sha
    if explicit_sha is not None and explicit_sha.strip() != header_sha:
        print(
            f"error: --sha {explicit_sha.strip()} disagrees with the snapshot in\n"
            f"  {specs_dir}, whose generated headers name platform commit\n"
            f"  {header_sha}. The baseline must pin the revision the snapshot\n"
            "  holds: regenerate the snapshot at the commit you mean, or drop --sha.",
            file=sys.stderr,
        )
        return ""
    return header_sha


def main() -> int:
    args = sys.argv[1:]
    specs_dir: Path | None = None
    explicit_sha: str | None = None
    i = 0
    while i < len(args):
        if args[i] == "--sha" and i + 1 < len(args):
            explicit_sha = args[i + 1]
            i += 2
            continue
        if specs_dir is None:
            specs_dir = Path(args[i])
        i += 1

    if specs_dir is None:
        print(
            "usage: python3 scripts/wire_shape/refresh.py <specs_dir> "
            "[--sha <SHA>]",
            file=sys.stderr,
        )
        return 2
    if not specs_dir.is_dir():
        print(f"error: {specs_dir} is not a directory", file=sys.stderr)
        return 2

    sha = _pinned_sha(specs_dir, explicit_sha)
    if not sha:
        return 2

    merged, cross_spec, intra_file = load_all_schemas(specs_dir)
    sdk = discover_sdk_types()

    registered: list[str] = []
    per_type_drift: dict[str, dict[str, list[str]]] = {}
    for name, sdk_fields in sdk.items():
        spec_fields = merged.get(name)
        if spec_fields is None:
            continue
        registered.append(name)
        sdk_only = difference(sdk_fields, spec_fields)
        spec_only = difference(spec_fields, sdk_fields)
        if not sdk_only and not spec_only:
            continue
        per_type_drift[name] = {"sdk_only": sdk_only, "spec_only": spec_only}
    registered.sort()

    baseline = {
        "_comment": (
            "Baseline of KNOWN wire-shape drift between the Java SDK and the "
            "OpenAPI specs. Generated by scripts/wire_shape/refresh.py. The "
            "CI gate fails on drift OUTSIDE this baseline. Entries here "
            "should be burned down over time via targeted fix PRs. See "
            "axonflow-enterprise tracking issue (QF-14 follow-up)."
        ),
        "openapi_specs_sha": sha,
        "cross_spec_duplicates": {k: dict(sorted(v.items())) for k, v in sorted(cross_spec.items())},
        "intra_file_duplicates": {k: dict(sorted(v.items())) for k, v in sorted(intra_file.items())},
        "registered_types": registered,
        "per_type_drift": dict(sorted(per_type_drift.items())),
    }

    write_baseline(baseline)
    try:
        rel = BASELINE_PATH.relative_to(REPO_ROOT)
    except ValueError:
        rel = BASELINE_PATH
    print(f"Wrote baseline: {rel}")
    print(f"  openapi_specs_sha:       {sha}")
    print(f"  cross_spec_duplicates:   {len(cross_spec)}")
    print(f"  intra_file_duplicates:   {len(intra_file)} file(s)")
    print(f"  registered_types:        {len(registered)}")
    print(f"  per_type_drift:          {len(per_type_drift)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
