#!/usr/bin/env python3
"""Regenerate tests/fixtures/wire-shape-baseline.json from a local
checkout of getaxonflow/axonflow's docs/api directory.

Usage:
    python3 scripts/wire_shape/refresh.py <specs_dir> [--sha <SHA>]

When --sha is omitted, the script tries `git -C <specs_dir>
rev-parse HEAD` to pin the commit. If neither is available, it
exits non-zero rather than write a baseline with an empty
openapi_specs_sha (the next CI run would fail at bootstrap).

The baseline is written atomically (temp-file + rename) so a
mid-encode crash can't leave a truncated file behind.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib import (  # noqa: E402
    BASELINE_PATH,
    REPO_ROOT,
    difference,
    discover_sdk_types,
    load_all_schemas,
    write_baseline,
)


def _git_head_sha(directory: Path) -> str:
    try:
        out = subprocess.check_output(
            ["git", "-C", str(directory), "rev-parse", "HEAD"],
            stderr=subprocess.DEVNULL,
        )
        return out.decode().strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def main() -> int:
    args = sys.argv[1:]
    specs_dir: Path | None = None
    explicit_sha: str | None = None
    i = 0
    while i < len(args):
        if args[i] == "--sha" and i + 1 < len(args):
            explicit_sha = args[i + 1]
            i += 2
            continue
        if specs_dir is None:
            specs_dir = Path(args[i])
        i += 1

    if specs_dir is None:
        print(
            "usage: python3 scripts/wire_shape/refresh.py <specs_dir> "
            "[--sha <SHA>]",
            file=sys.stderr,
        )
        return 2
    if not specs_dir.is_dir():
        print(f"error: {specs_dir} is not a directory", file=sys.stderr)
        return 2

    sha = (explicit_sha if explicit_sha is not None else _git_head_sha(specs_dir)).strip()
    if not sha:
        print(
            "error: could not determine OpenAPI specs commit SHA.\n"
            "  Either run this script against a specs_dir that sits inside a git\n"
            "  checkout of the getaxonflow/axonflow community mirror, or pass\n"
            "  --sha <commit-sha> explicitly. An empty SHA would poison\n"
            "  tests/fixtures/wire-shape-baseline.json and break the next CI\n"
            "  wire-shape-contract run at bootstrap.",
            file=sys.stderr,
        )
        return 2

    merged, cross_spec, intra_file = load_all_schemas(specs_dir)
    sdk = discover_sdk_types()

    registered: list[str] = []
    per_type_drift: dict[str, dict[str, list[str]]] = {}
    for name, sdk_fields in sdk.items():
        spec_fields = merged.get(name)
        if spec_fields is None:
            continue
        registered.append(name)
        sdk_only = difference(sdk_fields, spec_fields)
        spec_only = difference(spec_fields, sdk_fields)
        if not sdk_only and not spec_only:
            continue
        per_type_drift[name] = {"sdk_only": sdk_only, "spec_only": spec_only}
    registered.sort()

    baseline = {
        "_comment": (
            "Baseline of KNOWN wire-shape drift between the Java SDK and the "
            "OpenAPI specs. Generated by scripts/wire_shape/refresh.py. The "
            "CI gate fails on drift OUTSIDE this baseline. Entries here "
            "should be burned down over time via targeted fix PRs. See "
            "axonflow-enterprise tracking issue (QF-14 follow-up)."
        ),
        "openapi_specs_sha": sha,
        "cross_spec_duplicates": {k: dict(sorted(v.items())) for k, v in sorted(cross_spec.items())},
        "intra_file_duplicates": {k: dict(sorted(v.items())) for k, v in sorted(intra_file.items())},
        "registered_types": registered,
        "per_type_drift": dict(sorted(per_type_drift.items())),
    }

    write_baseline(baseline)
    try:
        rel = BASELINE_PATH.relative_to(REPO_ROOT)
    except ValueError:
        rel = BASELINE_PATH
    print(f"Wrote baseline: {rel}")
    print(f"  openapi_specs_sha:       {sha}")
    print(f"  cross_spec_duplicates:   {len(cross_spec)}")
    print(f"  intra_file_duplicates:   {len(intra_file)} file(s)")
    print(f"  registered_types:        {len(registered)}")
    print(f"  per_type_drift:          {len(per_type_drift)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
