/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:04f63f4d97215faa9fbf2b6a5152630f7310edbe47440b975d0f66ad63df811f
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A canonical identifier. Display names, emails, token claims, connector names and aliases are
 * never identifiers.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class AuthZENIdentifier {

  @JsonProperty("kind")
  private AuthZENIdentifierKind kind;

  @JsonProperty("type")
  private String type;

  @JsonProperty("qualifier")
  private String qualifier;

  @JsonProperty("local")
  private String local;

  /** Jackson, and a caller that prefers to set members one at a time. */
  public AuthZENIdentifier() {}

  /**
   * Builds a value carrying every member the contract requires.
   *
   * <p>Optional members start empty and are set with their fluent setter, so a member added to the
   * contract later becomes a compile error at NO call site that did not want it.
   *
   * @param kind the kind
   * @param type the type
   * @param local the local
   */
  public AuthZENIdentifier(AuthZENIdentifierKind kind, String type, String local) {
    this.kind = kind;
    this.type = type;
    this.local = local;
  }

  /**
   * @return the {@code kind} member
   */
  public AuthZENIdentifierKind getKind() {
    return kind;
  }

  /**
   * @param kind the {@code kind} member
   * @return this, for chaining
   */
  public AuthZENIdentifier setKind(AuthZENIdentifierKind kind) {
    this.kind = kind;
    return this;
  }

  /**
   * @return the {@code type} member
   */
  public String getType() {
    return type;
  }

  /**
   * @param type the {@code type} member
   * @return this, for chaining
   */
  public AuthZENIdentifier setType(String type) {
    this.type = type;
    return this;
  }

  /**
   * @return the {@code qualifier} member
   */
  public String getQualifier() {
    return qualifier;
  }

  /**
   * @param qualifier the {@code qualifier} member
   * @return this, for chaining
   */
  public AuthZENIdentifier setQualifier(String qualifier) {
    this.qualifier = qualifier;
    return this;
  }

  /**
   * @return the {@code local} member
   */
  public String getLocal() {
    return local;
  }

  /**
   * @param local the {@code local} member
   * @return this, for chaining
   */
  public AuthZENIdentifier setLocal(String local) {
    this.local = local;
    return this;
  }

  /**
   * Refuses this value if it does not carry what the server requires.
   *
   * <p>{@code at} is the JSON Pointer this value sits at in the envelope, so a refusal names the
   * same member the server would name. Pass {@code ""} at the root.
   *
   * @param at the JSON Pointer this value sits at
   * @throws AuthZENRefusedException if a contract rule is not satisfied
   */
  public void validate(String at) {
    if (kind == null || kind.value().isEmpty()) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/kind", "kind is required");
    }
    if (type == null || type.isEmpty()) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/type", "type is required");
    }
    if (local == null || local.isEmpty()) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/local", "local is required");
    }
  }
}
