/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:04f63f4d97215faa9fbf2b6a5152630f7310edbe47440b975d0f66ad63df811f
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * A closed set of values the server may send.
 *
 * <p>An unrecognised value is not a failure mode, it is a ROUND TRIP: a value a newer server added
 * after this build survives decode, re-encode and logging intact instead of collapsing onto a
 * neighbouring constant. It is, however, a reason not to branch on the value as though it were one
 * of the known ones — use {@link #isKnown()}.
 */
public final class AuthZENIdentifierKind {

  /** {@code organization} */
  public static final AuthZENIdentifierKind ORGANIZATION =
      new AuthZENIdentifierKind("organization");

  /** {@code principal} */
  public static final AuthZENIdentifierKind PRINCIPAL = new AuthZENIdentifierKind("principal");

  /** {@code group} */
  public static final AuthZENIdentifierKind GROUP = new AuthZENIdentifierKind("group");

  /** {@code resource} */
  public static final AuthZENIdentifierKind RESOURCE = new AuthZENIdentifierKind("resource");

  /** {@code action} */
  public static final AuthZENIdentifierKind ACTION = new AuthZENIdentifierKind("action");

  /** {@code tool} */
  public static final AuthZENIdentifierKind TOOL = new AuthZENIdentifierKind("tool");

  /** {@code client} */
  public static final AuthZENIdentifierKind CLIENT = new AuthZENIdentifierKind("client");

  /** {@code session} */
  public static final AuthZENIdentifierKind SESSION = new AuthZENIdentifierKind("session");

  /**
   * Every wire value this build knows, in artifact order.
   *
   * <p>This is the set a refusal names in its {@code supported} list, so it is the list a
   * diagnostic should print rather than one written beside it.
   */
  public static final List<String> KNOWN_WIRE_VALUES =
      Collections.unmodifiableList(
          Arrays.asList(
              "organization",
              "principal",
              "group",
              "resource",
              "action",
              "tool",
              "client",
              "session"));

  private final String value;

  private AuthZENIdentifierKind(String value) {
    this.value = value;
  }

  /**
   * The constant for {@code value}, or a carrier for one this build does not know.
   *
   * @param value the wire value
   * @return the corresponding instance, never null for a non-null input
   */
  @JsonCreator
  public static AuthZENIdentifierKind of(String value) {
    if (value == null) {
      return null;
    }
    if (ORGANIZATION.value.equals(value)) {
      return ORGANIZATION;
    }
    if (PRINCIPAL.value.equals(value)) {
      return PRINCIPAL;
    }
    if (GROUP.value.equals(value)) {
      return GROUP;
    }
    if (RESOURCE.value.equals(value)) {
      return RESOURCE;
    }
    if (ACTION.value.equals(value)) {
      return ACTION;
    }
    if (TOOL.value.equals(value)) {
      return TOOL;
    }
    if (CLIENT.value.equals(value)) {
      return CLIENT;
    }
    if (SESSION.value.equals(value)) {
      return SESSION;
    }
    return new AuthZENIdentifierKind(value);
  }

  /**
   * The wire value.
   *
   * @return the value as the server spells it
   */
  @JsonValue
  public String value() {
    return value;
  }

  /**
   * Whether this is a value this build knows.
   *
   * <p>A false result is not necessarily an error — a newer server may send a value added after
   * this SDK was built. It IS a reason not to treat it as equivalent to any known value.
   *
   * @return true when the value is one of {@link #KNOWN_WIRE_VALUES}
   */
  public boolean isKnown() {
    return KNOWN_WIRE_VALUES.contains(value);
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof AuthZENIdentifierKind)) {
      return false;
    }
    return value.equals(((AuthZENIdentifierKind) other).value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public String toString() {
    return value;
  }
}
