/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:647e16f769766f0ee8cf4913aaf5ac5c4567660fd2903da6766eead5db279efe
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The AuthZEN action object. */
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class AuthZENAction {

  @JsonProperty("name")
  private String name;

  @JsonInclude(JsonInclude.Include.NON_EMPTY)
  @JsonProperty("properties")
  private AttributeMap properties = new AttributeMap();

  /** Jackson, and a caller that prefers to set members one at a time. */
  public AuthZENAction() {}

  /**
   * Builds a value carrying every member the contract requires.
   *
   * <p>Optional members start empty and are set with their fluent setter, so a member added to the
   * contract later becomes a compile error at NO call site that did not want it.
   *
   * @param name the name
   */
  public AuthZENAction(String name) {
    this.name = name;
  }

  /**
   * @return the {@code name} member
   */
  public String getName() {
    return name;
  }

  /**
   * @param name the {@code name} member
   * @return this, for chaining
   */
  public AuthZENAction setName(String name) {
    this.name = name;
    return this;
  }

  /**
   * @return the {@code properties} member
   */
  public AttributeMap getProperties() {
    return properties;
  }

  /**
   * @param properties the {@code properties} member
   * @return this, for chaining
   */
  public AuthZENAction setProperties(AttributeMap properties) {
    this.properties = properties == null ? new AttributeMap() : properties;
    return this;
  }

  /**
   * Refuses this value if it does not carry what the server requires.
   *
   * <p>{@code at} is the JSON Pointer this value sits at in the envelope, so a refusal names the
   * same member the server would name. Pass {@code ""} at the root.
   *
   * @param at the JSON Pointer this value sits at
   * @throws AuthZENRefusedException if a contract rule is not satisfied
   */
  public void validate(String at) {
    if (name == null || name.isEmpty()) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/name", "name is required");
    }
    properties.validate(at + "/properties");
  }
}
