/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:04f63f4d97215faa9fbf2b6a5152630f7310edbe47440b975d0f66ad63df811f
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

/** Constants naming the contract these types were generated from. */
public final class AuthZENContract {

  private AuthZENContract() {}

  /**
   * The profile a Policy Enforcement Point negotiates to receive anything beyond the boolean
   * decision.
   *
   * <p>AuthZEN 1.0's response is a bare boolean. The four-valued state, the obligations, the
   * approval challenge and the safe reason code all ride in the response context and are returned
   * ONLY to a caller that asked for them by version, because handing a partial interpretation to a
   * caller that cannot act on it is worse than handing it the boolean it understands.
   */
  public static final String PROFILE_V1 = "axonflow-authzen-profile-2026-08-29";

  /**
   * The contract version these types were generated from. It is the value the server echoes in
   * {@code AuthZENResponseContext.schemaVersion}.
   */
  public static final String SCHEMA_VERSION = "2026-08-29";

  /**
   * The one route the AuthZEN surface is served on, and the request header the profile is
   * negotiated with.
   *
   * <p>Both are generated from the platform's contract through the artifact, not written here: a
   * rename on the platform is a regenerate-and-diff failure in this SDK, not a 404 in production
   * (axonflow-enterprise#3603).
   */
  public static final String PATH = "/api/v1/access/evaluation";

  /** The request header the AuthZEN profile is negotiated with; see {@link #PATH}. */
  public static final String PROFILE_HEADER = "X-Axonflow-AuthZEN-Profile";
}
