/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:647e16f769766f0ee8cf4913aaf5ac5c4567660fd2903da6766eead5db279efe
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The plural envelope: a shared subject, action, resource and context at the top level, with one
 * entry per decision. The number of decisions is fixed by the MAPPING, never by argument data, so
 * an empty evaluations array is malformed rather than a request for zero decisions.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class AuthZENBulk {

  @JsonProperty("subject")
  private AuthZENSubject subject;

  @JsonProperty("action")
  private AuthZENAction action;

  @JsonProperty("resource")
  private AuthZENResource resource;

  @JsonInclude(JsonInclude.Include.NON_EMPTY)
  @JsonProperty("context")
  private AttributeMap context = new AttributeMap();

  @JsonProperty("evaluations")
  private List<AuthZENRequest> evaluations;

  /** Jackson, and a caller that prefers to set members one at a time. */
  public AuthZENBulk() {}

  /**
   * Builds a value carrying every member the contract requires.
   *
   * <p>Optional members start empty and are set with their fluent setter, so a member added to the
   * contract later becomes a compile error at NO call site that did not want it.
   *
   * @param evaluations the evaluations
   */
  public AuthZENBulk(List<AuthZENRequest> evaluations) {
    this.evaluations = evaluations;
  }

  /**
   * @return the {@code subject} member
   */
  public AuthZENSubject getSubject() {
    return subject;
  }

  /**
   * @param subject the {@code subject} member
   * @return this, for chaining
   */
  public AuthZENBulk setSubject(AuthZENSubject subject) {
    this.subject = subject;
    return this;
  }

  /**
   * @return the {@code action} member
   */
  public AuthZENAction getAction() {
    return action;
  }

  /**
   * @param action the {@code action} member
   * @return this, for chaining
   */
  public AuthZENBulk setAction(AuthZENAction action) {
    this.action = action;
    return this;
  }

  /**
   * @return the {@code resource} member
   */
  public AuthZENResource getResource() {
    return resource;
  }

  /**
   * @param resource the {@code resource} member
   * @return this, for chaining
   */
  public AuthZENBulk setResource(AuthZENResource resource) {
    this.resource = resource;
    return this;
  }

  /**
   * @return the {@code context} member
   */
  public AttributeMap getContext() {
    return context;
  }

  /**
   * @param context the {@code context} member
   * @return this, for chaining
   */
  public AuthZENBulk setContext(AttributeMap context) {
    this.context = context == null ? new AttributeMap() : context;
    return this;
  }

  /**
   * @return the {@code evaluations} member
   */
  public List<AuthZENRequest> getEvaluations() {
    return evaluations;
  }

  /**
   * @param evaluations the {@code evaluations} member
   * @return this, for chaining
   */
  public AuthZENBulk setEvaluations(List<AuthZENRequest> evaluations) {
    this.evaluations = evaluations;
    return this;
  }

  /**
   * Refuses this value if it does not carry what the server requires.
   *
   * <p>{@code at} is the JSON Pointer this value sits at in the envelope, so a refusal names the
   * same member the server would name. Pass {@code ""} at the root.
   *
   * @param at the JSON Pointer this value sits at
   * @throws AuthZENRefusedException if a contract rule is not satisfied
   */
  public void validate(String at) {
    if (subject != null) {
      subject.validate(at + "/subject");
    }
    if (action != null) {
      action.validate(at + "/action");
    }
    if (resource != null) {
      resource.validate(at + "/resource");
    }
    context.validate(at + "/context");
    if (evaluations == null) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/evaluations", "evaluations is required");
    }
    if (evaluations == null || evaluations.size() < 1) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.MALFORMED_ENVELOPE,
          at + "/evaluations",
          "evaluations needs at least 1 entry");
    }
    if (evaluations != null) {
      for (int i = 0; i < evaluations.size(); i++) {
        evaluations.get(i).validate(at + "/evaluations" + "/" + i);
      }
    }
  }
}
