/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:647e16f769766f0ee8cf4913aaf5ac5c4567660fd2903da6766eead5db279efe
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Collections;
import java.util.List;

/**
 * The versioned AxonFlow profile payload. It is present only for a Policy Enforcement Point that
 * NEGOTIATED the profile; one that did not receives the boolean alone, because handing a partial
 * interpretation to a plane that cannot act on it is the failure ADR-065 invariant 12 forbids.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class AuthZENResponseContext {

  /** The only value the server sends is {@code axonflow-authzen-profile-2026-08-29}. */
  @JsonProperty("profile")
  private String profile;

  @JsonProperty("state")
  private AuthZENOperationalState state;

  @JsonProperty("category")
  private AuthZENCategory category;

  @JsonProperty("reason")
  private AuthZENReasonCode reason;

  @JsonInclude(JsonInclude.Include.NON_EMPTY)
  @JsonProperty("obligations")
  private List<AuthZENObligation> obligations;

  @JsonProperty("approval")
  private AuthZENApprovalRequirement approval;

  @JsonProperty("decision_id")
  private String decisionId;

  @JsonProperty("schema_version")
  private String schemaVersion;

  /** Jackson, and a caller that prefers to set members one at a time. */
  public AuthZENResponseContext() {}

  /**
   * Builds a value carrying every member the contract requires.
   *
   * <p>Optional members start empty and are set with their fluent setter, so a member added to the
   * contract later becomes a compile error at NO call site that did not want it.
   *
   * @param profile the profile
   * @param state the state
   * @param category the category
   * @param decisionId the decision_id
   * @param schemaVersion the schema_version
   */
  public AuthZENResponseContext(
      String profile,
      AuthZENOperationalState state,
      AuthZENCategory category,
      String decisionId,
      String schemaVersion) {
    this.profile = profile;
    this.state = state;
    this.category = category;
    this.decisionId = decisionId;
    this.schemaVersion = schemaVersion;
  }

  /**
   * @return the {@code profile} member
   */
  public String getProfile() {
    return profile;
  }

  /**
   * @param profile the {@code profile} member
   * @return this, for chaining
   */
  public AuthZENResponseContext setProfile(String profile) {
    this.profile = profile;
    return this;
  }

  /**
   * @return the {@code state} member
   */
  public AuthZENOperationalState getState() {
    return state;
  }

  /**
   * @param state the {@code state} member
   * @return this, for chaining
   */
  public AuthZENResponseContext setState(AuthZENOperationalState state) {
    this.state = state;
    return this;
  }

  /**
   * @return the {@code category} member
   */
  public AuthZENCategory getCategory() {
    return category;
  }

  /**
   * @param category the {@code category} member
   * @return this, for chaining
   */
  public AuthZENResponseContext setCategory(AuthZENCategory category) {
    this.category = category;
    return this;
  }

  /**
   * @return the {@code reason} member
   */
  public AuthZENReasonCode getReason() {
    return reason;
  }

  /**
   * @param reason the {@code reason} member
   * @return this, for chaining
   */
  public AuthZENResponseContext setReason(AuthZENReasonCode reason) {
    this.reason = reason;
    return this;
  }

  /**
   * The returned list is UNMODIFIABLE. Replace the member through the setter rather than mutating
   * what this returns.
   *
   * <p>The wrapper is not decoration. These types are the READ model for a decision an enforcement
   * point acts on, and every hand-written accessor over one of them already wraps - {@code
   * AuthZENDecision#getObligations()} does. Handing the internal list back unwrapped left the same
   * state reachable and writable one getter deeper, so an obligation could be added to, or a
   * mandatory one removed from, a decision that had already been handed out.
   *
   * <p>{@code null} is returned unchanged rather than as an empty list: an absent member and an
   * empty one are different bytes on the wire, and the validator refuses an absent required member
   * by name.
   *
   * @return the {@code obligations} member
   */
  public List<AuthZENObligation> getObligations() {
    return obligations == null ? null : Collections.unmodifiableList(obligations);
  }

  /**
   * @param obligations the {@code obligations} member
   * @return this, for chaining
   */
  public AuthZENResponseContext setObligations(List<AuthZENObligation> obligations) {
    this.obligations = obligations;
    return this;
  }

  /**
   * @return the {@code approval} member
   */
  public AuthZENApprovalRequirement getApproval() {
    return approval;
  }

  /**
   * @param approval the {@code approval} member
   * @return this, for chaining
   */
  public AuthZENResponseContext setApproval(AuthZENApprovalRequirement approval) {
    this.approval = approval;
    return this;
  }

  /**
   * @return the {@code decision_id} member
   */
  public String getDecisionId() {
    return decisionId;
  }

  /**
   * @param decisionId the {@code decision_id} member
   * @return this, for chaining
   */
  public AuthZENResponseContext setDecisionId(String decisionId) {
    this.decisionId = decisionId;
    return this;
  }

  /**
   * @return the {@code schema_version} member
   */
  public String getSchemaVersion() {
    return schemaVersion;
  }

  /**
   * @param schemaVersion the {@code schema_version} member
   * @return this, for chaining
   */
  public AuthZENResponseContext setSchemaVersion(String schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

  /**
   * Refuses this value if it does not carry what the server requires.
   *
   * <p>{@code at} is the JSON Pointer this value sits at in the envelope, so a refusal names the
   * same member the server would name. Pass {@code ""} at the root.
   *
   * @param at the JSON Pointer this value sits at
   * @throws AuthZENRefusedException if a contract rule is not satisfied
   */
  public void validate(String at) {
    if (profile == null || profile.isEmpty()) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/profile", "profile is required");
    }
    if (profile != null && !"axonflow-authzen-profile-2026-08-29".equals(profile)) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.MALFORMED_ENVELOPE,
          at + "/profile",
          "profile must be axonflow-authzen-profile-2026-08-29, got " + profile);
    }
    if (state == null || state.value().isEmpty()) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/state", "state is required");
    }
    if (category == null || category.value().isEmpty()) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/category", "category is required");
    }
    if (obligations != null) {
      for (int i = 0; i < obligations.size(); i++) {
        obligations.get(i).validate(at + "/obligations" + "/" + i);
      }
    }
    if (approval != null) {
      approval.validate(at + "/approval");
    }
    if (decisionId == null || decisionId.isEmpty()) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/decision_id", "decision_id is required");
    }
    if (schemaVersion == null || schemaVersion.isEmpty()) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION,
          at + "/schema_version",
          "schema_version is required");
    }
  }
}
