/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:647e16f769766f0ee8cf4913aaf5ac5c4567660fd2903da6766eead5db279efe
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * One immutable threshold clause: a quorum of distinct approvers drawn from a named eligible set.
 * It is named here rather than inlined under approval_requirement so it corresponds one-to-one with
 * the Go ApprovalClause, which is what lets the drift guard compare it and every SDK generate it as
 * a type rather than an anonymous shape.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class AuthZENApprovalClause {

  @JsonProperty("quorum")
  private Integer quorum;

  @JsonProperty("eligible")
  private List<AuthZENIdentifier> eligible;

  /** Jackson, and a caller that prefers to set members one at a time. */
  public AuthZENApprovalClause() {}

  /**
   * Builds a value carrying every member the contract requires.
   *
   * <p>Optional members start empty and are set with their fluent setter, so a member added to the
   * contract later becomes a compile error at NO call site that did not want it.
   *
   * @param quorum the quorum
   * @param eligible the eligible
   */
  public AuthZENApprovalClause(Integer quorum, List<AuthZENIdentifier> eligible) {
    this.quorum = quorum;
    this.eligible = eligible;
  }

  /**
   * @return the {@code quorum} member
   */
  public Integer getQuorum() {
    return quorum;
  }

  /**
   * @param quorum the {@code quorum} member
   * @return this, for chaining
   */
  public AuthZENApprovalClause setQuorum(Integer quorum) {
    this.quorum = quorum;
    return this;
  }

  /**
   * @return the {@code eligible} member
   */
  public List<AuthZENIdentifier> getEligible() {
    return eligible;
  }

  /**
   * @param eligible the {@code eligible} member
   * @return this, for chaining
   */
  public AuthZENApprovalClause setEligible(List<AuthZENIdentifier> eligible) {
    this.eligible = eligible;
    return this;
  }

  /**
   * Refuses this value if it does not carry what the server requires.
   *
   * <p>{@code at} is the JSON Pointer this value sits at in the envelope, so a refusal names the
   * same member the server would name. Pass {@code ""} at the root.
   *
   * @param at the JSON Pointer this value sits at
   * @throws AuthZENRefusedException if a contract rule is not satisfied
   */
  public void validate(String at) {
    if (quorum == null) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/quorum", "quorum is required");
    }
    if (eligible == null) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/eligible", "eligible is required");
    }
    if (eligible == null || eligible.size() < 1) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.MALFORMED_ENVELOPE, at + "/eligible", "eligible needs at least 1 entry");
    }
    if (eligible != null) {
      for (int i = 0; i < eligible.size(); i++) {
        eligible.get(i).validate(at + "/eligible" + "/" + i);
      }
    }
  }
}
