/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:647e16f769766f0ee8cf4913aaf5ac5c4567660fd2903da6766eead5db279efe
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The AuthZEN resource object. */
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class AuthZENResource {

  @JsonProperty("type")
  private String type;

  @JsonProperty("id")
  private String id;

  @JsonInclude(JsonInclude.Include.NON_EMPTY)
  @JsonProperty("properties")
  private AttributeMap properties = new AttributeMap();

  /** Jackson, and a caller that prefers to set members one at a time. */
  public AuthZENResource() {}

  /**
   * Builds a value carrying every member the contract requires.
   *
   * <p>Optional members start empty and are set with their fluent setter, so a member added to the
   * contract later becomes a compile error at NO call site that did not want it.
   *
   * @param type the type
   * @param id the id
   */
  public AuthZENResource(String type, String id) {
    this.type = type;
    this.id = id;
  }

  /**
   * @return the {@code type} member
   */
  public String getType() {
    return type;
  }

  /**
   * @param type the {@code type} member
   * @return this, for chaining
   */
  public AuthZENResource setType(String type) {
    this.type = type;
    return this;
  }

  /**
   * @return the {@code id} member
   */
  public String getId() {
    return id;
  }

  /**
   * @param id the {@code id} member
   * @return this, for chaining
   */
  public AuthZENResource setId(String id) {
    this.id = id;
    return this;
  }

  /**
   * @return the {@code properties} member
   */
  public AttributeMap getProperties() {
    return properties;
  }

  /**
   * @param properties the {@code properties} member
   * @return this, for chaining
   */
  public AuthZENResource setProperties(AttributeMap properties) {
    this.properties = properties;
    return this;
  }

  /**
   * Refuses this value if it does not carry what the server requires.
   *
   * <p>{@code at} is the JSON Pointer this value sits at in the envelope, so a refusal names the
   * same member the server would name. Pass {@code ""} at the root.
   *
   * @param at the JSON Pointer this value sits at
   * @throws AuthZENRefusedException if a contract rule is not satisfied
   */
  public void validate(String at) {
    if (type == null || type.isEmpty()) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/type", "type is required");
    }
    if (id == null || id.isEmpty()) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/id", "id is required");
    }
    if (properties != null) {
      properties.validate(at + "/properties");
    }
  }
}
