/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:647e16f769766f0ee8cf4913aaf5ac5c4567660fd2903da6766eead5db279efe
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Collections;
import java.util.List;

/**
 * The structured refusal body, returned when a request could not be EVALUATED. It is a separate
 * shape from the response rather than an extra member on it, because a refusal is not a decision: a
 * response carrying decision=false says the request was evaluated and denied, and returning that
 * for a request that was never evaluated would make 'denied' and 'unevaluable' the same event in
 * every audit and every client branch.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class AuthZENError {

  @JsonProperty("code")
  private AuthZENErrorCode code;

  @JsonProperty("pointer")
  private String pointer;

  @JsonProperty("message")
  private String message;

  @JsonInclude(JsonInclude.Include.NON_EMPTY)
  @JsonProperty("supported")
  private List<String> supported;

  @JsonProperty("request_id")
  private String requestId;

  /** Jackson, and a caller that prefers to set members one at a time. */
  public AuthZENError() {}

  /**
   * Builds a value carrying every member the contract requires.
   *
   * <p>Optional members start empty and are set with their fluent setter, so a member added to the
   * contract later becomes a compile error at NO call site that did not want it.
   *
   * @param code the code
   * @param message the message
   */
  public AuthZENError(AuthZENErrorCode code, String message) {
    this.code = code;
    this.message = message;
  }

  /**
   * @return the {@code code} member
   */
  public AuthZENErrorCode getCode() {
    return code;
  }

  /**
   * @param code the {@code code} member
   * @return this, for chaining
   */
  public AuthZENError setCode(AuthZENErrorCode code) {
    this.code = code;
    return this;
  }

  /**
   * @return the {@code pointer} member
   */
  public String getPointer() {
    return pointer;
  }

  /**
   * @param pointer the {@code pointer} member
   * @return this, for chaining
   */
  public AuthZENError setPointer(String pointer) {
    this.pointer = pointer;
    return this;
  }

  /**
   * @return the {@code message} member
   */
  public String getMessage() {
    return message;
  }

  /**
   * @param message the {@code message} member
   * @return this, for chaining
   */
  public AuthZENError setMessage(String message) {
    this.message = message;
    return this;
  }

  /**
   * The returned list is UNMODIFIABLE. Replace the member through the setter rather than mutating
   * what this returns.
   *
   * <p>The wrapper is not decoration. These types are the READ model for a decision an enforcement
   * point acts on, and every hand-written accessor over one of them already wraps - {@code
   * AuthZENDecision#getObligations()} does. Handing the internal list back unwrapped left the same
   * state reachable and writable one getter deeper, so an obligation could be added to, or a
   * mandatory one removed from, a decision that had already been handed out.
   *
   * <p>{@code null} is returned unchanged rather than as an empty list: an absent member and an
   * empty one are different bytes on the wire, and the validator refuses an absent required member
   * by name.
   *
   * @return the {@code supported} member
   */
  public List<String> getSupported() {
    return supported == null ? null : Collections.unmodifiableList(supported);
  }

  /**
   * @param supported the {@code supported} member
   * @return this, for chaining
   */
  public AuthZENError setSupported(List<String> supported) {
    this.supported = supported;
    return this;
  }

  /**
   * @return the {@code request_id} member
   */
  public String getRequestId() {
    return requestId;
  }

  /**
   * @param requestId the {@code request_id} member
   * @return this, for chaining
   */
  public AuthZENError setRequestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

  /**
   * Refuses this value if it does not carry what the server requires.
   *
   * <p>{@code at} is the JSON Pointer this value sits at in the envelope, so a refusal names the
   * same member the server would name. Pass {@code ""} at the root.
   *
   * @param at the JSON Pointer this value sits at
   * @throws AuthZENRefusedException if a contract rule is not satisfied
   */
  public void validate(String at) {
    if (code == null || code.value().isEmpty()) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/code", "code is required");
    }
    if (message == null || message.isEmpty()) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/message", "message is required");
    }
  }
}
