/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:647e16f769766f0ee8cf4913aaf5ac5c4567660fd2903da6766eead5db279efe
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * A closed set of values the server may send.
 *
 * <p>An unrecognised value is not a failure mode, it is a ROUND TRIP: a value a newer server added
 * after this build survives decode, re-encode and logging intact instead of collapsing onto a
 * neighbouring constant. It is, however, a reason not to branch on the value as though it were one
 * of the known ones — use {@link #isKnown()}.
 */
public final class AuthZENCategory {

  /** {@code allowed} */
  public static final AuthZENCategory ALLOWED = new AuthZENCategory("allowed");

  /** {@code not_permitted} */
  public static final AuthZENCategory NOT_PERMITTED = new AuthZENCategory("not_permitted");

  /** {@code approval_required} */
  public static final AuthZENCategory APPROVAL_REQUIRED = new AuthZENCategory("approval_required");

  /** {@code temporarily_unavailable} */
  public static final AuthZENCategory TEMPORARILY_UNAVAILABLE =
      new AuthZENCategory("temporarily_unavailable");

  /** {@code invalid_request} */
  public static final AuthZENCategory INVALID_REQUEST = new AuthZENCategory("invalid_request");

  /**
   * Every wire value this build knows, in artifact order.
   *
   * <p>This is the set a refusal names in its {@code supported} list, so it is the list a
   * diagnostic should print rather than one written beside it.
   */
  public static final List<String> KNOWN_WIRE_VALUES =
      Collections.unmodifiableList(
          Arrays.asList(
              "allowed",
              "not_permitted",
              "approval_required",
              "temporarily_unavailable",
              "invalid_request"));

  private final String value;

  private AuthZENCategory(String value) {
    this.value = value;
  }

  /**
   * The constant for {@code value}, or a carrier for one this build does not know.
   *
   * @param value the wire value
   * @return the corresponding instance, never null for a non-null input
   */
  @JsonCreator
  public static AuthZENCategory of(String value) {
    if (value == null) {
      return null;
    }
    if (ALLOWED.value.equals(value)) {
      return ALLOWED;
    }
    if (NOT_PERMITTED.value.equals(value)) {
      return NOT_PERMITTED;
    }
    if (APPROVAL_REQUIRED.value.equals(value)) {
      return APPROVAL_REQUIRED;
    }
    if (TEMPORARILY_UNAVAILABLE.value.equals(value)) {
      return TEMPORARILY_UNAVAILABLE;
    }
    if (INVALID_REQUEST.value.equals(value)) {
      return INVALID_REQUEST;
    }
    return new AuthZENCategory(value);
  }

  /**
   * The wire value.
   *
   * @return the value as the server spells it
   */
  @JsonValue
  public String value() {
    return value;
  }

  /**
   * Whether this is a value this build knows.
   *
   * <p>A false result is not necessarily an error — a newer server may send a value added after
   * this SDK was built. It IS a reason not to treat it as equivalent to any known value.
   *
   * @return true when the value is one of {@link #KNOWN_WIRE_VALUES}
   */
  public boolean isKnown() {
    return KNOWN_WIRE_VALUES.contains(value);
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof AuthZENCategory)) {
      return false;
    }
    return value.equals(((AuthZENCategory) other).value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public String toString() {
    return value;
  }
}
