/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:04f63f4d97215faa9fbf2b6a5152630f7310edbe47440b975d0f66ad63df811f
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * A closed set of values the server may send.
 *
 * <p>An unrecognised value is not a failure mode, it is a ROUND TRIP: a value a newer server added
 * after this build survives decode, re-encode and logging intact instead of collapsing onto a
 * neighbouring constant. It is, however, a reason not to branch on the value as though it were one
 * of the known ones — use {@link #isKnown()}.
 */
public final class AuthZENReasonCode {

  /** {@code permitted} */
  public static final AuthZENReasonCode PERMITTED = new AuthZENReasonCode("permitted");

  /** {@code approval_required} */
  public static final AuthZENReasonCode APPROVAL_REQUIRED =
      new AuthZENReasonCode("approval_required");

  /** {@code explicit_constraint} */
  public static final AuthZENReasonCode EXPLICIT_CONSTRAINT =
      new AuthZENReasonCode("explicit_constraint");

  /** {@code no_matching_permission} */
  public static final AuthZENReasonCode NO_MATCHING_PERMISSION =
      new AuthZENReasonCode("no_matching_permission");

  /** {@code unknown_constraint} */
  public static final AuthZENReasonCode UNKNOWN_CONSTRAINT =
      new AuthZENReasonCode("unknown_constraint");

  /** {@code unknown_permission} */
  public static final AuthZENReasonCode UNKNOWN_PERMISSION =
      new AuthZENReasonCode("unknown_permission");

  /** {@code unknown_requirement} */
  public static final AuthZENReasonCode UNKNOWN_REQUIREMENT =
      new AuthZENReasonCode("unknown_requirement");

  /** {@code invalid_input} */
  public static final AuthZENReasonCode INVALID_INPUT = new AuthZENReasonCode("invalid_input");

  /** {@code evaluation_error} */
  public static final AuthZENReasonCode EVALUATION_ERROR =
      new AuthZENReasonCode("evaluation_error");

  /** {@code unsupported_obligation} */
  public static final AuthZENReasonCode UNSUPPORTED_OBLIGATION =
      new AuthZENReasonCode("unsupported_obligation");

  /** {@code obligation_conflict} */
  public static final AuthZENReasonCode OBLIGATION_CONFLICT =
      new AuthZENReasonCode("obligation_conflict");

  /** {@code unknown_action} */
  public static final AuthZENReasonCode UNKNOWN_ACTION = new AuthZENReasonCode("unknown_action");

  /** {@code unknown_realm} */
  public static final AuthZENReasonCode UNKNOWN_REALM = new AuthZENReasonCode("unknown_realm");

  /** {@code schema_violation} */
  public static final AuthZENReasonCode SCHEMA_VIOLATION =
      new AuthZENReasonCode("schema_violation");

  /** {@code delegation_depth_exceeded} */
  public static final AuthZENReasonCode DELEGATION_DEPTH_EXCEEDED =
      new AuthZENReasonCode("delegation_depth_exceeded");

  /** {@code budget_exhausted} */
  public static final AuthZENReasonCode BUDGET_EXHAUSTED =
      new AuthZENReasonCode("budget_exhausted");

  /** {@code binding_mismatch} */
  public static final AuthZENReasonCode BINDING_MISMATCH =
      new AuthZENReasonCode("binding_mismatch");

  /** {@code approval_unsatisfiable} */
  public static final AuthZENReasonCode APPROVAL_UNSATISFIABLE =
      new AuthZENReasonCode("approval_unsatisfiable");

  /** {@code approval_expired} */
  public static final AuthZENReasonCode APPROVAL_EXPIRED =
      new AuthZENReasonCode("approval_expired");

  /** {@code authoring_rejected} */
  public static final AuthZENReasonCode AUTHORING_REJECTED =
      new AuthZENReasonCode("authoring_rejected");

  /**
   * Every wire value this build knows, in artifact order.
   *
   * <p>This is the set a refusal names in its {@code supported} list, so it is the list a
   * diagnostic should print rather than one written beside it.
   */
  public static final List<String> KNOWN_WIRE_VALUES =
      Collections.unmodifiableList(
          Arrays.asList(
              "permitted",
              "approval_required",
              "explicit_constraint",
              "no_matching_permission",
              "unknown_constraint",
              "unknown_permission",
              "unknown_requirement",
              "invalid_input",
              "evaluation_error",
              "unsupported_obligation",
              "obligation_conflict",
              "unknown_action",
              "unknown_realm",
              "schema_violation",
              "delegation_depth_exceeded",
              "budget_exhausted",
              "binding_mismatch",
              "approval_unsatisfiable",
              "approval_expired",
              "authoring_rejected"));

  private final String value;

  private AuthZENReasonCode(String value) {
    this.value = value;
  }

  /**
   * The constant for {@code value}, or a carrier for one this build does not know.
   *
   * @param value the wire value
   * @return the corresponding instance, never null for a non-null input
   */
  @JsonCreator
  public static AuthZENReasonCode of(String value) {
    if (value == null) {
      return null;
    }
    if (PERMITTED.value.equals(value)) {
      return PERMITTED;
    }
    if (APPROVAL_REQUIRED.value.equals(value)) {
      return APPROVAL_REQUIRED;
    }
    if (EXPLICIT_CONSTRAINT.value.equals(value)) {
      return EXPLICIT_CONSTRAINT;
    }
    if (NO_MATCHING_PERMISSION.value.equals(value)) {
      return NO_MATCHING_PERMISSION;
    }
    if (UNKNOWN_CONSTRAINT.value.equals(value)) {
      return UNKNOWN_CONSTRAINT;
    }
    if (UNKNOWN_PERMISSION.value.equals(value)) {
      return UNKNOWN_PERMISSION;
    }
    if (UNKNOWN_REQUIREMENT.value.equals(value)) {
      return UNKNOWN_REQUIREMENT;
    }
    if (INVALID_INPUT.value.equals(value)) {
      return INVALID_INPUT;
    }
    if (EVALUATION_ERROR.value.equals(value)) {
      return EVALUATION_ERROR;
    }
    if (UNSUPPORTED_OBLIGATION.value.equals(value)) {
      return UNSUPPORTED_OBLIGATION;
    }
    if (OBLIGATION_CONFLICT.value.equals(value)) {
      return OBLIGATION_CONFLICT;
    }
    if (UNKNOWN_ACTION.value.equals(value)) {
      return UNKNOWN_ACTION;
    }
    if (UNKNOWN_REALM.value.equals(value)) {
      return UNKNOWN_REALM;
    }
    if (SCHEMA_VIOLATION.value.equals(value)) {
      return SCHEMA_VIOLATION;
    }
    if (DELEGATION_DEPTH_EXCEEDED.value.equals(value)) {
      return DELEGATION_DEPTH_EXCEEDED;
    }
    if (BUDGET_EXHAUSTED.value.equals(value)) {
      return BUDGET_EXHAUSTED;
    }
    if (BINDING_MISMATCH.value.equals(value)) {
      return BINDING_MISMATCH;
    }
    if (APPROVAL_UNSATISFIABLE.value.equals(value)) {
      return APPROVAL_UNSATISFIABLE;
    }
    if (APPROVAL_EXPIRED.value.equals(value)) {
      return APPROVAL_EXPIRED;
    }
    if (AUTHORING_REJECTED.value.equals(value)) {
      return AUTHORING_REJECTED;
    }
    return new AuthZENReasonCode(value);
  }

  /**
   * The wire value.
   *
   * @return the value as the server spells it
   */
  @JsonValue
  public String value() {
    return value;
  }

  /**
   * Whether this is a value this build knows.
   *
   * <p>A false result is not necessarily an error — a newer server may send a value added after
   * this SDK was built. It IS a reason not to treat it as equivalent to any known value.
   *
   * @return true when the value is one of {@link #KNOWN_WIRE_VALUES}
   */
  public boolean isKnown() {
    return KNOWN_WIRE_VALUES.contains(value);
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof AuthZENReasonCode)) {
      return false;
    }
    return value.equals(((AuthZENReasonCode) other).value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public String toString() {
    return value;
  }
}
