/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:04f63f4d97215faa9fbf2b6a5152630f7310edbe47440b975d0f66ad63df811f
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * One subject-action-resource-context evaluation. Every member is structurally OPTIONAL here
 * because a plural-envelope entry inherits any member it omits from the envelope's shared base. The
 * completeness invariant - that the MERGED entry carries a subject, an action and a resource - is a
 * cross-object property this document cannot express, and AuthZENEnvelope.Project enforces it. A
 * validator that passes this schema has therefore NOT established completeness, which is why the
 * singular member below carries its own required list.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class AuthZENRequest {

  @JsonProperty("subject")
  private AuthZENSubject subject;

  @JsonProperty("action")
  private AuthZENAction action;

  @JsonProperty("resource")
  private AuthZENResource resource;

  @JsonInclude(JsonInclude.Include.NON_EMPTY)
  @JsonProperty("context")
  private AttributeMap context = new AttributeMap();

  /** Jackson, and a caller that prefers to set members one at a time. */
  public AuthZENRequest() {}

  /**
   * @return the {@code subject} member
   */
  public AuthZENSubject getSubject() {
    return subject;
  }

  /**
   * @param subject the {@code subject} member
   * @return this, for chaining
   */
  public AuthZENRequest setSubject(AuthZENSubject subject) {
    this.subject = subject;
    return this;
  }

  /**
   * @return the {@code action} member
   */
  public AuthZENAction getAction() {
    return action;
  }

  /**
   * @param action the {@code action} member
   * @return this, for chaining
   */
  public AuthZENRequest setAction(AuthZENAction action) {
    this.action = action;
    return this;
  }

  /**
   * @return the {@code resource} member
   */
  public AuthZENResource getResource() {
    return resource;
  }

  /**
   * @param resource the {@code resource} member
   * @return this, for chaining
   */
  public AuthZENRequest setResource(AuthZENResource resource) {
    this.resource = resource;
    return this;
  }

  /**
   * @return the {@code context} member
   */
  public AttributeMap getContext() {
    return context;
  }

  /**
   * @param context the {@code context} member
   * @return this, for chaining
   */
  public AuthZENRequest setContext(AttributeMap context) {
    this.context = context == null ? new AttributeMap() : context;
    return this;
  }

  /**
   * Refuses this value if it does not carry what the server requires.
   *
   * <p>{@code at} is the JSON Pointer this value sits at in the envelope, so a refusal names the
   * same member the server would name. Pass {@code ""} at the root.
   *
   * @param at the JSON Pointer this value sits at
   * @throws AuthZENRefusedException if a contract rule is not satisfied
   */
  public void validate(String at) {
    if (subject != null) {
      subject.validate(at + "/subject");
    }
    if (action != null) {
      action.validate(at + "/action");
    }
    if (resource != null) {
      resource.validate(at + "/resource");
    }
    context.validate(at + "/context");
  }
}
