/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:647e16f769766f0ee8cf4913aaf5ac5c4567660fd2903da6766eead5db279efe
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * A closed set of values the server may send.
 *
 * <p>An unrecognised value is not a failure mode, it is a ROUND TRIP: a value a newer server added
 * after this build survives decode, re-encode and logging intact instead of collapsing onto a
 * neighbouring constant. It is, however, a reason not to branch on the value as though it were one
 * of the known ones — use {@link #isKnown()}.
 */
public final class AuthZENObligationType {

  /** {@code approval_challenge} */
  public static final AuthZENObligationType APPROVAL_CHALLENGE =
      new AuthZENObligationType("approval_challenge");

  /** {@code field_remove} */
  public static final AuthZENObligationType FIELD_REMOVE =
      new AuthZENObligationType("field_remove");

  /** {@code field_redact} */
  public static final AuthZENObligationType FIELD_REDACT =
      new AuthZENObligationType("field_redact");

  /** {@code field_hash} */
  public static final AuthZENObligationType FIELD_HASH = new AuthZENObligationType("field_hash");

  /** {@code field_mask} */
  public static final AuthZENObligationType FIELD_MASK = new AuthZENObligationType("field_mask");

  /** {@code field_annotate} */
  public static final AuthZENObligationType FIELD_ANNOTATE =
      new AuthZENObligationType("field_annotate");

  /** {@code field_tokenize} */
  public static final AuthZENObligationType FIELD_TOKENIZE =
      new AuthZENObligationType("field_tokenize");

  /** {@code schema_transform} */
  public static final AuthZENObligationType SCHEMA_TRANSFORM =
      new AuthZENObligationType("schema_transform");

  /** {@code response_filter} */
  public static final AuthZENObligationType RESPONSE_FILTER =
      new AuthZENObligationType("response_filter");

  /** {@code route_restriction} */
  public static final AuthZENObligationType ROUTE_RESTRICTION =
      new AuthZENObligationType("route_restriction");

  /** {@code step_up_authentication} */
  public static final AuthZENObligationType STEP_UP_AUTHENTICATION =
      new AuthZENObligationType("step_up_authentication");

  /** {@code quota_reservation} */
  public static final AuthZENObligationType QUOTA_RESERVATION =
      new AuthZENObligationType("quota_reservation");

  /** {@code immutable_audit} */
  public static final AuthZENObligationType IMMUTABLE_AUDIT =
      new AuthZENObligationType("immutable_audit");

  /** {@code notification} */
  public static final AuthZENObligationType NOTIFICATION =
      new AuthZENObligationType("notification");

  /**
   * Every wire value this build knows, in artifact order.
   *
   * <p>This is the set a refusal names in its {@code supported} list, so it is the list a
   * diagnostic should print rather than one written beside it.
   */
  public static final List<String> KNOWN_WIRE_VALUES =
      Collections.unmodifiableList(
          Arrays.asList(
              "approval_challenge",
              "field_remove",
              "field_redact",
              "field_hash",
              "field_mask",
              "field_annotate",
              "field_tokenize",
              "schema_transform",
              "response_filter",
              "route_restriction",
              "step_up_authentication",
              "quota_reservation",
              "immutable_audit",
              "notification"));

  private final String value;

  private AuthZENObligationType(String value) {
    this.value = value;
  }

  /**
   * The constant for {@code value}, or a carrier for one this build does not know.
   *
   * @param value the wire value
   * @return the corresponding instance, never null for a non-null input
   */
  @JsonCreator
  public static AuthZENObligationType of(String value) {
    if (value == null) {
      return null;
    }
    if (APPROVAL_CHALLENGE.value.equals(value)) {
      return APPROVAL_CHALLENGE;
    }
    if (FIELD_REMOVE.value.equals(value)) {
      return FIELD_REMOVE;
    }
    if (FIELD_REDACT.value.equals(value)) {
      return FIELD_REDACT;
    }
    if (FIELD_HASH.value.equals(value)) {
      return FIELD_HASH;
    }
    if (FIELD_MASK.value.equals(value)) {
      return FIELD_MASK;
    }
    if (FIELD_ANNOTATE.value.equals(value)) {
      return FIELD_ANNOTATE;
    }
    if (FIELD_TOKENIZE.value.equals(value)) {
      return FIELD_TOKENIZE;
    }
    if (SCHEMA_TRANSFORM.value.equals(value)) {
      return SCHEMA_TRANSFORM;
    }
    if (RESPONSE_FILTER.value.equals(value)) {
      return RESPONSE_FILTER;
    }
    if (ROUTE_RESTRICTION.value.equals(value)) {
      return ROUTE_RESTRICTION;
    }
    if (STEP_UP_AUTHENTICATION.value.equals(value)) {
      return STEP_UP_AUTHENTICATION;
    }
    if (QUOTA_RESERVATION.value.equals(value)) {
      return QUOTA_RESERVATION;
    }
    if (IMMUTABLE_AUDIT.value.equals(value)) {
      return IMMUTABLE_AUDIT;
    }
    if (NOTIFICATION.value.equals(value)) {
      return NOTIFICATION;
    }
    return new AuthZENObligationType(value);
  }

  /**
   * The wire value.
   *
   * @return the value as the server spells it
   */
  @JsonValue
  public String value() {
    return value;
  }

  /**
   * Whether this is a value this build knows.
   *
   * <p>A false result is not necessarily an error — a newer server may send a value added after
   * this SDK was built. It IS a reason not to treat it as equivalent to any known value.
   *
   * @return true when the value is one of {@link #KNOWN_WIRE_VALUES}
   */
  public boolean isKnown() {
    return KNOWN_WIRE_VALUES.contains(value);
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof AuthZENObligationType)) {
      return false;
    }
    return value.equals(((AuthZENObligationType) other).value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public String toString() {
    return value;
  }
}
