/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:647e16f769766f0ee8cf4913aaf5ac5c4567660fd2903da6766eead5db279efe
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/** One typed instruction owned by a named enforcement component. */
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class AuthZENObligation {

  @JsonProperty("type")
  private AuthZENObligationType type;

  @JsonProperty("target")
  private String target;

  @JsonInclude(JsonInclude.Include.NON_EMPTY)
  @JsonProperty("params")
  private Map<String, String> params;

  @JsonProperty("mandatory")
  private Boolean mandatory;

  @JsonProperty("source_policy")
  private String sourcePolicy;

  @JsonProperty("schema_version")
  private Integer schemaVersion;

  /** Jackson, and a caller that prefers to set members one at a time. */
  public AuthZENObligation() {}

  /**
   * Builds a value carrying every member the contract requires.
   *
   * <p>Optional members start empty and are set with their fluent setter, so a member added to the
   * contract later becomes a compile error at NO call site that did not want it.
   *
   * @param type the type
   * @param mandatory the mandatory
   * @param sourcePolicy the source_policy
   * @param schemaVersion the schema_version
   */
  public AuthZENObligation(
      AuthZENObligationType type, Boolean mandatory, String sourcePolicy, Integer schemaVersion) {
    this.type = type;
    this.mandatory = mandatory;
    this.sourcePolicy = sourcePolicy;
    this.schemaVersion = schemaVersion;
  }

  /**
   * @return the {@code type} member
   */
  public AuthZENObligationType getType() {
    return type;
  }

  /**
   * @param type the {@code type} member
   * @return this, for chaining
   */
  public AuthZENObligation setType(AuthZENObligationType type) {
    this.type = type;
    return this;
  }

  /**
   * @return the {@code target} member
   */
  public String getTarget() {
    return target;
  }

  /**
   * @param target the {@code target} member
   * @return this, for chaining
   */
  public AuthZENObligation setTarget(String target) {
    this.target = target;
    return this;
  }

  /**
   * @return the {@code params} member
   */
  public Map<String, String> getParams() {
    return params;
  }

  /**
   * @param params the {@code params} member
   * @return this, for chaining
   */
  public AuthZENObligation setParams(Map<String, String> params) {
    this.params = params;
    return this;
  }

  /**
   * @return the {@code mandatory} member
   */
  public Boolean getMandatory() {
    return mandatory;
  }

  /**
   * @param mandatory the {@code mandatory} member
   * @return this, for chaining
   */
  public AuthZENObligation setMandatory(Boolean mandatory) {
    this.mandatory = mandatory;
    return this;
  }

  /**
   * @return the {@code source_policy} member
   */
  public String getSourcePolicy() {
    return sourcePolicy;
  }

  /**
   * @param sourcePolicy the {@code source_policy} member
   * @return this, for chaining
   */
  public AuthZENObligation setSourcePolicy(String sourcePolicy) {
    this.sourcePolicy = sourcePolicy;
    return this;
  }

  /**
   * @return the {@code schema_version} member
   */
  public Integer getSchemaVersion() {
    return schemaVersion;
  }

  /**
   * @param schemaVersion the {@code schema_version} member
   * @return this, for chaining
   */
  public AuthZENObligation setSchemaVersion(Integer schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

  /**
   * Refuses this value if it does not carry what the server requires.
   *
   * <p>{@code at} is the JSON Pointer this value sits at in the envelope, so a refusal names the
   * same member the server would name. Pass {@code ""} at the root.
   *
   * @param at the JSON Pointer this value sits at
   * @throws AuthZENRefusedException if a contract rule is not satisfied
   */
  public void validate(String at) {
    if (type == null || type.value().isEmpty()) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/type", "type is required");
    }
    if (target != null && target.length() < 1) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION,
          at + "/target",
          "target needs at least 1 character");
    }
    if (mandatory == null) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/mandatory", "mandatory is required");
    }
    if (sourcePolicy == null || sourcePolicy.isEmpty()) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION,
          at + "/source_policy",
          "source_policy is required");
    }
    if (schemaVersion == null) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION,
          at + "/schema_version",
          "schema_version is required");
    }
  }
}
