/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:04f63f4d97215faa9fbf2b6a5152630f7310edbe47440b975d0f66ad63df811f
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * A closed set of values the server may send.
 *
 * <p>An unrecognised value is not a failure mode, it is a ROUND TRIP: a value a newer server added
 * after this build survives decode, re-encode and logging intact instead of collapsing onto a
 * neighbouring constant. It is, however, a reason not to branch on the value as though it were one
 * of the known ones — use {@link #isKnown()}.
 */
public final class AuthZENErrorCode {

  /** {@code malformed_envelope} */
  public static final AuthZENErrorCode MALFORMED_ENVELOPE =
      new AuthZENErrorCode("malformed_envelope");

  /** {@code incomplete_evaluation} */
  public static final AuthZENErrorCode INCOMPLETE_EVALUATION =
      new AuthZENErrorCode("incomplete_evaluation");

  /** {@code unsupported_subject} */
  public static final AuthZENErrorCode UNSUPPORTED_SUBJECT =
      new AuthZENErrorCode("unsupported_subject");

  /** {@code unsupported_action} */
  public static final AuthZENErrorCode UNSUPPORTED_ACTION =
      new AuthZENErrorCode("unsupported_action");

  /** {@code unsupported_resource} */
  public static final AuthZENErrorCode UNSUPPORTED_RESOURCE =
      new AuthZENErrorCode("unsupported_resource");

  /** {@code unevaluable_attribute} */
  public static final AuthZENErrorCode UNEVALUABLE_ATTRIBUTE =
      new AuthZENErrorCode("unevaluable_attribute");

  /** {@code missing_evaluable_content} */
  public static final AuthZENErrorCode MISSING_EVALUABLE_CONTENT =
      new AuthZENErrorCode("missing_evaluable_content");

  /** {@code evaluation_unavailable} */
  public static final AuthZENErrorCode EVALUATION_UNAVAILABLE =
      new AuthZENErrorCode("evaluation_unavailable");

  /**
   * Every wire value this build knows, in artifact order.
   *
   * <p>This is the set a refusal names in its {@code supported} list, so it is the list a
   * diagnostic should print rather than one written beside it.
   */
  public static final List<String> KNOWN_WIRE_VALUES =
      Collections.unmodifiableList(
          Arrays.asList(
              "malformed_envelope",
              "incomplete_evaluation",
              "unsupported_subject",
              "unsupported_action",
              "unsupported_resource",
              "unevaluable_attribute",
              "missing_evaluable_content",
              "evaluation_unavailable"));

  private final String value;

  private AuthZENErrorCode(String value) {
    this.value = value;
  }

  /**
   * The constant for {@code value}, or a carrier for one this build does not know.
   *
   * @param value the wire value
   * @return the corresponding instance, never null for a non-null input
   */
  @JsonCreator
  public static AuthZENErrorCode of(String value) {
    if (value == null) {
      return null;
    }
    if (MALFORMED_ENVELOPE.value.equals(value)) {
      return MALFORMED_ENVELOPE;
    }
    if (INCOMPLETE_EVALUATION.value.equals(value)) {
      return INCOMPLETE_EVALUATION;
    }
    if (UNSUPPORTED_SUBJECT.value.equals(value)) {
      return UNSUPPORTED_SUBJECT;
    }
    if (UNSUPPORTED_ACTION.value.equals(value)) {
      return UNSUPPORTED_ACTION;
    }
    if (UNSUPPORTED_RESOURCE.value.equals(value)) {
      return UNSUPPORTED_RESOURCE;
    }
    if (UNEVALUABLE_ATTRIBUTE.value.equals(value)) {
      return UNEVALUABLE_ATTRIBUTE;
    }
    if (MISSING_EVALUABLE_CONTENT.value.equals(value)) {
      return MISSING_EVALUABLE_CONTENT;
    }
    if (EVALUATION_UNAVAILABLE.value.equals(value)) {
      return EVALUATION_UNAVAILABLE;
    }
    return new AuthZENErrorCode(value);
  }

  /**
   * The wire value.
   *
   * @return the value as the server spells it
   */
  @JsonValue
  public String value() {
    return value;
  }

  /**
   * Whether this is a value this build knows.
   *
   * <p>A false result is not necessarily an error — a newer server may send a value added after
   * this SDK was built. It IS a reason not to treat it as equivalent to any known value.
   *
   * @return true when the value is one of {@link #KNOWN_WIRE_VALUES}
   */
  public boolean isKnown() {
    return KNOWN_WIRE_VALUES.contains(value);
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof AuthZENErrorCode)) {
      return false;
    }
    return value.equals(((AuthZENErrorCode) other).value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public String toString() {
    return value;
  }
}
