/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:647e16f769766f0ee8cf4913aaf5ac5c4567660fd2903da6766eead5db279efe
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

/** Constants naming the contract these types were generated from. */
public final class AuthZENContract {

  private AuthZENContract() {}

  /**
   * The profile a Policy Enforcement Point negotiates to receive anything beyond the boolean
   * decision.
   *
   * <p>AuthZEN 1.0's response is a bare boolean. The four-valued state, the obligations, the
   * approval challenge and the safe reason code all ride in the response context and are returned
   * ONLY to a caller that asked for them by version, because handing a partial interpretation to a
   * caller that cannot act on it is worse than handing it the boolean it understands.
   */
  public static final String PROFILE_V1 = "axonflow-authzen-profile-2026-08-29";

  /**
   * The contract version these types were generated from. It is the value the server echoes in
   * {@code AuthZENResponseContext.schemaVersion}.
   */
  public static final String SCHEMA_VERSION = "2026-08-29";
}
