/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:647e16f769766f0ee8cf4913aaf5ac5c4567660fd2903da6766eead5db279efe
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * A conjunction of immutable threshold clauses. Clauses are never collapsed by pool intersection or
 * union.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class AuthZENApprovalRequirement {

  @JsonProperty("all_of")
  private List<AuthZENApprovalClause> allOf;

  @JsonProperty("separation_of_duties")
  private boolean separationOfDuties;

  @JsonProperty("expires_at")
  private String expiresAt;

  /** Jackson, and a caller that prefers to set members one at a time. */
  public AuthZENApprovalRequirement() {}

  /**
   * Builds a value carrying every member the contract requires.
   *
   * <p>Optional members start empty and are set with their fluent setter, so a member added to the
   * contract later becomes a compile error at NO call site that did not want it.
   *
   * @param allOf the all_of
   * @param separationOfDuties the separation_of_duties
   * @param expiresAt the expires_at
   */
  public AuthZENApprovalRequirement(
      List<AuthZENApprovalClause> allOf, boolean separationOfDuties, String expiresAt) {
    this.allOf = allOf;
    this.separationOfDuties = separationOfDuties;
    this.expiresAt = expiresAt;
  }

  /**
   * @return the {@code all_of} member
   */
  public List<AuthZENApprovalClause> getAllOf() {
    return allOf;
  }

  /**
   * @param allOf the {@code all_of} member
   * @return this, for chaining
   */
  public AuthZENApprovalRequirement setAllOf(List<AuthZENApprovalClause> allOf) {
    this.allOf = allOf;
    return this;
  }

  /**
   * @return the {@code separation_of_duties} member
   */
  public boolean getSeparationOfDuties() {
    return separationOfDuties;
  }

  /**
   * @param separationOfDuties the {@code separation_of_duties} member
   * @return this, for chaining
   */
  public AuthZENApprovalRequirement setSeparationOfDuties(boolean separationOfDuties) {
    this.separationOfDuties = separationOfDuties;
    return this;
  }

  /**
   * @return the {@code expires_at} member
   */
  public String getExpiresAt() {
    return expiresAt;
  }

  /**
   * @param expiresAt the {@code expires_at} member
   * @return this, for chaining
   */
  public AuthZENApprovalRequirement setExpiresAt(String expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Refuses this value if it does not carry what the server requires.
   *
   * <p>{@code at} is the JSON Pointer this value sits at in the envelope, so a refusal names the
   * same member the server would name. Pass {@code ""} at the root.
   *
   * @param at the JSON Pointer this value sits at
   * @throws AuthZENRefusedException if a contract rule is not satisfied
   */
  public void validate(String at) {
    if (allOf == null) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/all_of", "all_of is required");
    }
    if (allOf == null || allOf.size() < 1) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.MALFORMED_ENVELOPE, at + "/all_of", "all_of needs at least 1 entry");
    }
    if (allOf != null) {
      for (int i = 0; i < allOf.size(); i++) {
        allOf.get(i).validate(at + "/all_of" + "/" + i);
      }
    }
    if (expiresAt == null || expiresAt.isEmpty()) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/expires_at", "expires_at is required");
    }
  }
}
