/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:647e16f769766f0ee8cf4913aaf5ac5c4567660fd2903da6766eead5db279efe
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The top level. Exactly two members are defined and exactly one may be PRESENT. Presence is
 * decided on the KEY SET, not on a decoded pointer, so {"evaluation": {...}, "evaluations": null}
 * carries both declared members and is malformed.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class AuthZENEnvelope {

  /**
   * The singular member. Unlike a plural entry it has no shared base to inherit from, so it must
   * carry its own subject, action and resource.
   */
  @JsonProperty("evaluation")
  private AuthZENRequest evaluation;

  @JsonProperty("evaluations")
  private AuthZENBulk evaluations;

  /** Jackson, and a caller that prefers to set members one at a time. */
  public AuthZENEnvelope() {}

  /**
   * @return the {@code evaluation} member
   */
  public AuthZENRequest getEvaluation() {
    return evaluation;
  }

  /**
   * @param evaluation the {@code evaluation} member
   * @return this, for chaining
   */
  public AuthZENEnvelope setEvaluation(AuthZENRequest evaluation) {
    this.evaluation = evaluation;
    return this;
  }

  /**
   * @return the {@code evaluations} member
   */
  public AuthZENBulk getEvaluations() {
    return evaluations;
  }

  /**
   * @param evaluations the {@code evaluations} member
   * @return this, for chaining
   */
  public AuthZENEnvelope setEvaluations(AuthZENBulk evaluations) {
    this.evaluations = evaluations;
    return this;
  }

  /**
   * Refuses this value if it does not carry what the server requires.
   *
   * <p>{@code at} is the JSON Pointer this value sits at in the envelope, so a refusal names the
   * same member the server would name. Pass {@code ""} at the root.
   *
   * @param at the JSON Pointer this value sits at
   * @throws AuthZENRefusedException if a contract rule is not satisfied
   */
  public void validate(String at) {
    int present = 0;
    if (evaluation != null) {
      present++;
    }
    if (evaluations != null) {
      present++;
    }
    if (present != 1) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.MALFORMED_ENVELOPE,
          at,
          "exactly one of evaluation or evaluations must be present, " + present + " are");
    }
    if (evaluation != null && evaluation.getAction() == null) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION,
          at + "/evaluation/action",
          "evaluation has no action; it has no shared base to inherit one from");
    }
    if (evaluation != null && evaluation.getResource() == null) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION,
          at + "/evaluation/resource",
          "evaluation has no resource; it has no shared base to inherit one from");
    }
    if (evaluation != null && evaluation.getSubject() == null) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION,
          at + "/evaluation/subject",
          "evaluation has no subject; it has no shared base to inherit one from");
    }
    if (evaluation != null) {
      evaluation.validate(at + "/evaluation");
    }
    if (evaluations != null) {
      evaluations.validate(at + "/evaluations");
    }
  }
}
