/*
 * Code generated by ./scripts/gen-authzen-types.sh. DO NOT EDIT.
 *
 * Source: testdata/authzen-surface.json
 *   artifact:        axonflow-authzen-surface v1
 *   profile:         axonflow-authzen-profile-2026-08-29
 *   contract schema: 2026-08-29
 *   schema digest:   sha256:647e16f769766f0ee8cf4913aaf5ac5c4567660fd2903da6766eead5db279efe
 *
 * Regenerate with:
 *
 *   ./scripts/gen-authzen-types.sh
 *
 * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest
 * regenerates it in memory and compares bytes, so a hand edit fails CI on the
 * next run.
 */
package com.getaxonflow.sdk.authzen;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The AuthZEN reply. `decision` is the collapsed boolean: ALLOW is true and every other state is
 * false. It is the only member an un-negotiated enforcement point receives.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class AuthZENResponse {

  @JsonProperty("decision")
  private Boolean decision;

  @JsonProperty("context")
  private AuthZENResponseContext context;

  /** Jackson, and a caller that prefers to set members one at a time. */
  public AuthZENResponse() {}

  /**
   * Builds a value carrying every member the contract requires.
   *
   * <p>Optional members start empty and are set with their fluent setter, so a member added to the
   * contract later becomes a compile error at NO call site that did not want it.
   *
   * @param decision the decision
   */
  public AuthZENResponse(Boolean decision) {
    this.decision = decision;
  }

  /**
   * @return the {@code decision} member
   */
  public Boolean getDecision() {
    return decision;
  }

  /**
   * @param decision the {@code decision} member
   * @return this, for chaining
   */
  public AuthZENResponse setDecision(Boolean decision) {
    this.decision = decision;
    return this;
  }

  /**
   * @return the {@code context} member
   */
  public AuthZENResponseContext getContext() {
    return context;
  }

  /**
   * @param context the {@code context} member
   * @return this, for chaining
   */
  public AuthZENResponse setContext(AuthZENResponseContext context) {
    this.context = context;
    return this;
  }

  /**
   * Refuses this value if it does not carry what the server requires.
   *
   * <p>{@code at} is the JSON Pointer this value sits at in the envelope, so a refusal names the
   * same member the server would name. Pass {@code ""} at the root.
   *
   * @param at the JSON Pointer this value sits at
   * @throws AuthZENRefusedException if a contract rule is not satisfied
   */
  public void validate(String at) {
    if (decision == null) {
      throw AuthZENRefusedException.of(
          AuthZENErrorCode.INCOMPLETE_EVALUATION, at + "/decision", "decision is required");
    }
    if (context != null) {
      context.validate(at + "/context");
    }
  }
}
