/*
 * Copyright 2026 AxonFlow
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.getaxonflow.sdk.authzen.codegen;

import com.getaxonflow.sdk.authzen.codegen.Surface.EnumDecl;
import com.getaxonflow.sdk.authzen.codegen.Surface.FieldDecl;
import com.getaxonflow.sdk.authzen.codegen.Surface.SurfaceException;
import com.getaxonflow.sdk.authzen.codegen.Surface.TypeDecl;
import com.getaxonflow.sdk.authzen.codegen.Surface.TypeRef;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * The emitter: artifact in, one Java source file per declared type and enum out.
 *
 * <h2>Why the types are generated rather than written</h2>
 *
 * <p>The AuthZEN surface ships in five SDKs. Hand-transcribing the same twenty shapes five times
 * produces five slightly different opinions about which fields are optional, and the resulting
 * drift does not look like a bug: it looks like one SDK marking a field required that the others
 * mark optional, discovered by a customer whose request one SDK sends happily and another rejects.
 * The platform reduces its canonical JSON Schema to {@code testdata/authzen-surface.json}, every
 * SDK generates from that one file, and each repository's CI regenerates and diffs.
 *
 * <h2>Two rules this emitter carries that an annotation cannot</h2>
 *
 * <ol>
 *   <li>The envelope's exactly-one-of, and the singular member's own required set. Both are
 *       properties of a POSITION rather than of a type, so no field annotation can express them.
 *   <li>{@code kind: "object"} is not {@code Map<String, Object>}. In this artifact every {@code
 *       object} member is a bag of attributes the CALLER resolved from somewhere else, and the type
 *       for a resolved attribute has three states, not two. See {@code Attribute}.
 * </ol>
 *
 * <h2>What is deliberately NOT here: unknown-member strictness</h2>
 *
 * <p>An unknown member in a decision is a server speaking a profile this build does not understand,
 * and reading the rest is acting on a partial interpretation of an authorization decision. The
 * generated classes carry NO annotation for that, and the first version of this emitter was wrong
 * about why they could: {@code @JsonIgnoreProperties(ignoreUnknown = false)} is Jackson's DEFAULT,
 * and it only declines to ignore — whether that becomes a failure is the mapper's {@code
 * FAIL_ON_UNKNOWN_PROPERTIES}, which the SDK's shared mapper turns OFF. The annotation was a
 * no-op that read as a guarantee, and a test decoding a decision with an extra member passed
 * straight through it.
 *
 * <p>The strictness therefore lives where it can actually take effect: {@code AxonFlow} decodes
 * this surface with a COPY of its mapper that has the feature on. See {@code
 * AxonFlow.authzenReader}.
 *
 * <p>Layout follows google-java-format, reproduced rather than invoked — see {@link Layout}.
 */
public final class Emitter {

  /** Where the generated sources land, relative to the SDK root. */
  public static final String OUTPUT_DIR = "src/main/java/com/getaxonflow/sdk/authzen";

  /** Where the vendored contract artifact lives, relative to the SDK root. */
  public static final String SURFACE_PATH = "testdata/authzen-surface.json";

  /** The command that regenerates the output. */
  public static final String REGENERATE_COMMAND = "./scripts/gen-authzen-types.sh";

  /** The marker every generated file carries in its header. */
  public static final String GENERATED_MARKER = "Code generated by";

  private static final String PACKAGE = "com.getaxonflow.sdk.authzen";

  private Emitter() {}

  /**
   * Renders every file the artifact describes.
   *
   * @param s the parsed artifact
   * @return file name to file content, in a deterministic order
   */
  public static Map<String, String> emit(Surface s) {
    if (s.types.isEmpty() || s.enums.isEmpty()) {
      throw new SurfaceException(
          "the artifact describes "
              + s.types.size()
              + " type(s) and "
              + s.enums.size()
              + " enum(s); generating from an empty surface would silently produce an empty SDK");
    }
    if (!"axonflow-authzen-surface".equals(s.artifact)) {
      throw new SurfaceException(
          SURFACE_PATH + " is not an AuthZEN surface artifact (artifact=\"" + s.artifact + "\")");
    }
    if (s.artifactVersion != 1) {
      throw new SurfaceException(
          "artifact format version "
              + s.artifactVersion
              + " is not supported by this emitter; a format change is a deliberate migration, not"
              + " something to generate through");
    }

    Map<String, String> out = new LinkedHashMap<>();
    out.put("AuthZENContract.java", emitContract(s));
    for (EnumDecl e : s.enums) {
      out.put(typeName(e.name) + ".java", emitEnum(s, e));
    }
    for (TypeDecl t : s.types) {
      out.put(typeName(t.name) + ".java", emitType(s, t));
    }
    return out;
  }

  // -------------------------------------------------------------------------
  // File scaffolding
  // -------------------------------------------------------------------------

  /**
   * The header, as a BLOCK comment.
   *
   * <p>google-java-format reflows Javadoc and leaves block comments alone, so the provenance lines
   * stay aligned however long the digest gets.
   */
  private static String header(Surface s) {
    return "/*\n"
        + " * Code generated by "
        + REGENERATE_COMMAND
        + ". DO NOT EDIT.\n"
        + " *\n"
        + " * Source: "
        + SURFACE_PATH
        + "\n"
        + " *   artifact:        "
        + s.artifact
        + " v"
        + s.artifactVersion
        + "\n"
        + " *   profile:         "
        + s.profile
        + "\n"
        + " *   contract schema: "
        + s.contractSchemaVersion
        + "\n"
        + " *   schema digest:   "
        + s.sourceSchemaSha256
        + "\n"
        + " *\n"
        + " * Regenerate with:\n"
        + " *\n"
        + " *   "
        + REGENERATE_COMMAND
        + "\n"
        + " *\n"
        + " * Editing this file by hand is pointless: AuthZENGeneratedTypesAreCurrentTest\n"
        + " * regenerates it in memory and compares bytes, so a hand edit fails CI on the\n"
        + " * next run.\n"
        + " */\n"
        + "package "
        + PACKAGE
        + ";\n\n";
  }

  private static String imports(Set<String> needed) {
    List<String> sorted = new ArrayList<>(needed);
    Collections.sort(sorted);
    StringBuilder b = new StringBuilder();
    for (String i : sorted) {
      b.append("import ").append(i).append(";\n");
    }
    if (!sorted.isEmpty()) {
      b.append("\n");
    }
    return b.toString();
  }

  /** Breaks a declaration after its {@code =} when the whole thing does not fit. */
  private static String assignment(String indent, String lhs, String rhs) {
    String oneLine = indent + lhs + " = " + rhs + ";";
    if (oneLine.length() <= Layout.MAX_WIDTH) {
      return oneLine + "\n";
    }
    return indent + lhs + " =\n" + indent + "    " + rhs + ";\n";
  }

  // -------------------------------------------------------------------------
  // The contract constants
  // -------------------------------------------------------------------------

  private static String emitContract(Surface s) {
    StringBuilder b = new StringBuilder(header(s));
    b.append(
        Layout.javadoc(
            "",
            Collections.singletonList(
                "Constants naming the contract these types were generated from."),
            Collections.<String>emptyList()));
    b.append("public final class AuthZENContract {\n\n");
    b.append("  private AuthZENContract() {}\n\n");
    b.append(
        Layout.javadoc(
            "  ",
            Arrays.asList(
                "The profile a Policy Enforcement Point negotiates to receive anything beyond the"
                    + " boolean decision.",
                "<p>AuthZEN 1.0's response is a bare boolean. The four-valued state, the"
                    + " obligations, the approval challenge and the safe reason code all ride in"
                    + " the response context and are returned ONLY to a caller that asked for them"
                    + " by version, because handing a partial interpretation to a caller that"
                    + " cannot act on it is worse than handing it the boolean it understands."),
            Collections.<String>emptyList()));
    b.append(assignment("  ", "public static final String PROFILE_V1", "\"" + s.profile + "\""));
    b.append("\n");
    b.append(
        Layout.javadoc(
            "  ",
            Collections.singletonList(
                "The contract version these types were generated from. It is the value the server"
                    + " echoes in {@code AuthZENResponseContext.schemaVersion}."),
            Collections.<String>emptyList()));
    b.append(
        assignment(
            "  ",
            "public static final String SCHEMA_VERSION",
            "\"" + s.contractSchemaVersion + "\""));
    b.append("}\n");
    return b.toString();
  }

  // -------------------------------------------------------------------------
  // Enums
  // -------------------------------------------------------------------------

  /**
   * A closed set of wire values, rendered as a value CLASS rather than a Java {@code enum}.
   *
   * <p>A Java enum cannot carry a value it does not declare, so a value a newer server added after
   * this build would either throw during deserialisation or — with {@code
   * READ_UNKNOWN_ENUM_VALUES_AS_NULL} — become null, and a null operational state read as "not
   * ALLOW" is a decision this build never saw. A value class round-trips the string verbatim and
   * says so through {@code isKnown()}.
   */
  private static String emitEnum(Surface s, EnumDecl e) {
    String name = typeName(e.name);
    Set<String> needed =
        new HashSet<>(
            Arrays.asList(
                "com.fasterxml.jackson.annotation.JsonCreator",
                "com.fasterxml.jackson.annotation.JsonValue",
                "java.util.Arrays",
                "java.util.Collections",
                "java.util.List",
                "java.util.Objects"));

    List<String> classDoc = new ArrayList<>();
    if (!e.doc.isEmpty()) {
      classDoc.add(e.doc);
    }
    classDoc.add("A closed set of values the server may send.");
    classDoc.add(
        "<p>An unrecognised value is not a failure mode, it is a ROUND TRIP: a value a newer server"
            + " added after this build survives decode, re-encode and logging intact instead of"
            + " collapsing onto a neighbouring constant. It is, however, a reason not to branch on"
            + " the value as though it were one of the known ones — use {@link #isKnown()}.");

    StringBuilder b = new StringBuilder(header(s)).append(imports(needed));
    b.append(Layout.javadoc("", classDoc, Collections.<String>emptyList()));
    b.append("public final class ").append(name).append(" {\n\n");

    for (String v : e.values) {
      b.append("  /** {@code ").append(v).append("} */\n");
      b.append(
          assignment(
              "  ",
              "public static final " + name + " " + constantName(v),
              "new " + name + "(\"" + v + "\")"));
      b.append("\n");
    }

    b.append(
        Layout.javadoc(
            "  ",
            Arrays.asList(
                "Every wire value this build knows, in artifact order.",
                "<p>This is the set a refusal names in its {@code supported} list, so it is the"
                    + " list a diagnostic should print rather than one written beside it."),
            Collections.<String>emptyList()));
    b.append(knownWireValues(e.values)).append("\n");

    b.append("  private final String value;\n\n");
    b.append("  private ").append(name).append("(String value) {\n");
    b.append("    this.value = value;\n  }\n\n");

    b.append(
        Layout.javadoc(
            "  ",
            Collections.singletonList(
                "The constant for {@code value}, or a carrier for one this build does not know."),
            Arrays.asList(
                "@param value the wire value",
                "@return the corresponding instance, never null for a non-null input")));
    b.append("  @JsonCreator\n");
    b.append("  public static ").append(name).append(" of(String value) {\n");
    b.append("    if (value == null) {\n      return null;\n    }\n");
    for (String v : e.values) {
      b.append("    if (")
          .append(constantName(v))
          .append(".value.equals(value)) {\n      return ")
          .append(constantName(v))
          .append(";\n    }\n");
    }
    b.append("    return new ").append(name).append("(value);\n  }\n\n");

    b.append(
        Layout.javadoc(
            "  ",
            Collections.singletonList("The wire value."),
            Collections.singletonList("@return the value as the server spells it")));
    b.append("  @JsonValue\n  public String value() {\n    return value;\n  }\n\n");

    b.append(
        Layout.javadoc(
            "  ",
            Arrays.asList(
                "Whether this is a value this build knows.",
                "<p>A false result is not necessarily an error — a newer server may send a value"
                    + " added after this SDK was built. It IS a reason not to treat it as"
                    + " equivalent to any known value."),
            Collections.singletonList(
                "@return true when the value is one of {@link #KNOWN_WIRE_VALUES}")));
    b.append("  public boolean isKnown() {\n    return KNOWN_WIRE_VALUES.contains(value);\n  }\n\n");

    b.append("  @Override\n  public boolean equals(Object other) {\n");
    b.append("    if (this == other) {\n      return true;\n    }\n");
    b.append("    if (!(other instanceof ")
        .append(name)
        .append(")) {\n      return false;\n    }\n");
    b.append("    return value.equals(((").append(name).append(") other).value);\n  }\n\n");
    b.append("  @Override\n  public int hashCode() {\n    return Objects.hash(value);\n  }\n\n");
    b.append("  @Override\n  public String toString() {\n    return value;\n  }\n}\n");
    return b.toString();
  }

  /** Renders {@code KNOWN_WIRE_VALUES}, in whichever of the formatter's shapes fits. */
  private static String knownWireValues(List<String> values) {
    List<String> quoted = new ArrayList<>();
    for (String v : values) {
      quoted.add("\"" + v + "\"");
    }
    String lhs = "  public static final List<String> KNOWN_WIRE_VALUES =\n";
    String inline =
        "      Collections.unmodifiableList(Arrays.asList(" + String.join(", ", quoted) + "));";
    if (inline.length() <= Layout.MAX_WIDTH) {
      return lhs + inline + "\n";
    }
    StringBuilder b = new StringBuilder(lhs);
    b.append("      Collections.unmodifiableList(\n");
    b.append("          Arrays.asList(\n");
    for (int i = 0; i < quoted.size(); i++) {
      b.append("              ").append(quoted.get(i));
      b.append(i == quoted.size() - 1 ? "));" : ",").append("\n");
    }
    return b.toString();
  }

  // -------------------------------------------------------------------------
  // Structs
  // -------------------------------------------------------------------------

  private static String emitType(Surface s, TypeDecl t) {
    String name = typeName(t.name);
    Set<String> needed = new HashSet<>();
    needed.add("com.fasterxml.jackson.annotation.JsonInclude");
    needed.add("com.fasterxml.jackson.annotation.JsonProperty");
    for (FieldDecl f : t.fields) {
      collectImports(f.type, needed);
    }

    StringBuilder body = new StringBuilder();
    body.append(
        Layout.javadoc(
            "",
            Collections.singletonList(
                t.doc.isEmpty() ? "Part of the AuthZEN wire surface." : t.doc),
            Collections.<String>emptyList()));
    body.append("@JsonInclude(JsonInclude.Include.NON_NULL)\n");
    body.append("public final class ").append(name).append(" {\n\n");

    for (FieldDecl f : t.fields) {
      List<String> doc = new ArrayList<>();
      if (!f.doc.isEmpty()) {
        doc.add(f.doc);
      }
      if (!f.constant.isEmpty()) {
        doc.add("The only value the server sends is {@code " + f.constant + "}.");
      }
      if (!doc.isEmpty()) {
        body.append(Layout.javadoc("  ", doc, Collections.<String>emptyList()));
      }
      if (!f.required && isCollectionish(f.type)) {
        body.append("  @JsonInclude(JsonInclude.Include.NON_EMPTY)\n");
      }
      body.append("  @JsonProperty(\"").append(f.name).append("\")\n");
      String declaration = "private " + javaType(f) + " " + fieldName(f.name);
      String init = initialiser(f);
      if (init.isEmpty()) {
        body.append("  ").append(declaration).append(";\n\n");
      } else {
        body.append(assignment("  ", declaration, init)).append("\n");
      }
    }

    emitConstructors(body, name, t);
    emitAccessors(body, name, t);
    emitValidate(body, t);

    // The last member already ends with a blank line, and a blank line before
    // the closing brace is one the formatter removes.
    while (body.length() >= 2 && body.charAt(body.length() - 2) == '\n') {
      body.setLength(body.length() - 1);
    }
    body.append("}\n");
    return header(s) + imports(needed) + body;
  }

  private static void emitConstructors(StringBuilder b, String name, TypeDecl t) {
    b.append(
        Layout.javadoc(
            "  ",
            Collections.singletonList(
                "Jackson, and a caller that prefers to set members one at a time."),
            Collections.<String>emptyList()));
    b.append("  public ").append(name).append("() {}\n\n");

    List<FieldDecl> required = new ArrayList<>();
    for (FieldDecl f : t.fields) {
      if (f.required) {
        required.add(f);
      }
    }
    if (required.isEmpty()) {
      return;
    }
    List<String> tags = new ArrayList<>();
    for (FieldDecl f : required) {
      tags.add("@param " + fieldName(f.name) + " the " + f.name);
    }
    b.append(
        Layout.javadoc(
            "  ",
            Arrays.asList(
                "Builds a value carrying every member the contract requires.",
                "<p>Optional members start empty and are set with their fluent setter, so a member"
                    + " added to the contract later becomes a compile error at NO call site that"
                    + " did not want it."),
            tags));
    List<String> params = new ArrayList<>();
    for (FieldDecl f : required) {
      params.add(javaType(f) + " " + fieldName(f.name));
    }
    b.append(Layout.call("  ", "public " + name + "(", params, ") {"));
    for (FieldDecl f : required) {
      String field = fieldName(f.name);
      b.append("    this.").append(field).append(" = ").append(field).append(";\n");
    }
    b.append("  }\n\n");
  }

  private static void emitAccessors(StringBuilder b, String name, TypeDecl t) {
    for (FieldDecl f : t.fields) {
      String field = fieldName(f.name);
      String type = javaType(f);
      String upper = upperFirst(field);
      b.append(
          Layout.javadoc(
              "  ",
              Collections.<String>emptyList(),
              Collections.singletonList("@return the {@code " + f.name + "} member")));
      b.append("  public ").append(type).append(" get").append(upper).append("() {\n");
      b.append("    return ").append(field).append(";\n  }\n\n");

      b.append(
          Layout.javadoc(
              "  ",
              Collections.<String>emptyList(),
              Arrays.asList(
                  "@param " + field + " the {@code " + f.name + "} member",
                  "@return this, for chaining")));
      b.append(
          Layout.call(
              "  ",
              "public " + name + " set" + upper + "(",
              Collections.singletonList(type + " " + field),
              ") {"));
      if ("object".equals(f.type.kind)) {
        // A NULL attribute bag is not an empty one, and accepting null here was
        // a way to delete an unresolved attribute through a public setter:
        // `validate` guards `if (bag != null)`, so a request whose bag held an
        // `unknown` went out complete once somebody nulled the member. The
        // field's own invariant is "never null"; the setter now holds it.
        b.append("    this.")
            .append(field)
            .append(" = ")
            .append(field)
            .append(" == null ? new AttributeMap() : ")
            .append(field)
            .append(";\n");
      } else {
        b.append("    this.").append(field).append(" = ").append(field).append(";\n");
      }
      b.append("    return this;\n  }\n\n");
    }
  }

  /**
   * Renders the checks the type system cannot carry.
   *
   * <p>EVERY type gets one, including types with no constraint of their own. A type whose members
   * are all optional still OWNS the validation of those members: skipping it because "there is
   * nothing to check here" is how a parent reports OK while a child carries a violation the server
   * refuses.
   */
  private static void emitValidate(StringBuilder b, TypeDecl t) {
    b.append(
        Layout.javadoc(
            "  ",
            Arrays.asList(
                "Refuses this value if it does not carry what the server requires.",
                "<p>{@code at} is the JSON Pointer this value sits at in the envelope, so a refusal"
                    + " names the same member the server would name. Pass {@code \"\"} at the"
                    + " root."),
            Arrays.asList(
                "@param at the JSON Pointer this value sits at",
                "@throws AuthZENRefusedException if a contract rule is not satisfied")));
    b.append("  public void validate(String at) {\n");

    for (List<String> group : t.exactlyOneOf) {
      b.append("    int present = 0;\n");
      for (String m : group) {
        b.append("    if (").append(fieldName(m)).append(" != null) {\n      present++;\n    }\n");
      }
      b.append("    if (present != 1) {\n");
      b.append(
          refusal(
              "MALFORMED_ENVELOPE",
              "at",
              "\"exactly one of "
                  + String.join(" or ", group)
                  + " must be present, \" + present + \" are\""));
      b.append("    }\n");
    }

    for (FieldDecl f : t.fields) {
      String field = fieldName(f.name);
      String pointer = "at + \"/" + f.name + "\"";

      if (f.required) {
        String emptiness = null;
        if ("string".equals(f.type.kind)) {
          emptiness = field + " == null || " + field + ".isEmpty()";
        } else if ("enum".equals(f.type.kind)) {
          emptiness = field + " == null || " + field + ".value().isEmpty()";
        } else if ("ref".equals(f.type.kind)
            || "array".equals(f.type.kind)
            || "bool".equals(f.type.kind)
            || "int".equals(f.type.kind)) {
          // `bool` and `int` are here for the reason javaType explains: a
          // missing required primitive is invisible to both the decoder and any
          // check written against a primitive, and one of them is
          // `obligation.mandatory`.
          emptiness = field + " == null";
        }
        if (emptiness != null) {
          b.append("    if (").append(emptiness).append(") {\n");
          b.append(refusal("INCOMPLETE_EVALUATION", pointer, "\"" + f.name + " is required\""));
          b.append("    }\n");
        }
      }

      // A required string is already refused when empty, so `min_length: 1` on
      // one would emit a branch that can never be taken. An unreachable branch
      // in generated code is a branch no test can cover, and it teaches a reader
      // that the two checks are independent when they are not.
      if (f.minLength > 0 && (!f.required || f.minLength > 1)) {
        b.append("    if (")
            .append(field)
            .append(" != null && ")
            .append(field)
            .append(".length() < ")
            .append(f.minLength)
            .append(") {\n");
        b.append(
            refusal(
                "INCOMPLETE_EVALUATION",
                pointer,
                "\""
                    + f.name
                    + " needs at least "
                    + f.minLength
                    + " character"
                    + (f.minLength == 1 ? "" : "s")
                    + "\""));
        b.append("    }\n");
      }

      if (!f.constant.isEmpty()) {
        if (f.constant.indexOf('"') >= 0 || f.constant.indexOf('\\') >= 0) {
          throw new SurfaceException(
              "const values carrying a quote or a backslash are not supported: " + f.constant);
        }
        b.append("    if (")
            .append(field)
            .append(" != null && !\"")
            .append(f.constant)
            .append("\".equals(")
            .append(field)
            .append(")) {\n");
        b.append(
            refusal(
                "MALFORMED_ENVELOPE",
                pointer,
                "\"" + f.name + " must be " + f.constant + ", got \" + " + field));
        b.append("    }\n");
      }

      if (f.minItems > 0) {
        b.append("    if (")
            .append(field)
            .append(" == null || ")
            .append(field)
            .append(".size() < ")
            .append(f.minItems)
            .append(") {\n");
        b.append(
            refusal(
                "MALFORMED_ENVELOPE",
                pointer,
                "\""
                    + f.name
                    + " needs at least "
                    + f.minItems
                    + " entr"
                    + (f.minItems == 1 ? "y" : "ies")
                    + "\""));
        b.append("    }\n");
      }

      for (String m : f.requiresMembers) {
        b.append("    if (")
            .append(field)
            .append(" != null && ")
            .append(field)
            .append(".get")
            .append(upperFirst(fieldName(m)))
            .append("() == null) {\n");
        b.append(
            refusal(
                "INCOMPLETE_EVALUATION",
                "at + \"/" + f.name + "/" + m + "\"",
                "\"" + f.name + " has no " + m + "; it has no shared base to inherit one from\""));
        b.append("    }\n");
      }

      // Nested validation. Without it a parent reports OK while a child carries
      // a violation the server refuses.
      if ("object".equals(f.type.kind)) {
        // No null guard: the field is initialised to an empty bag and its setter
        // refuses null, so a guard here would only be a place for a future null
        // to hide - and what it would hide is an unresolved attribute.
        b.append("    ").append(field).append(".validate(").append(pointer).append(");\n");
      } else if ("ref".equals(f.type.kind)) {
        b.append("    if (").append(field).append(" != null) {\n      ");
        b.append(field).append(".validate(").append(pointer).append(");\n    }\n");
      } else if ("array".equals(f.type.kind)
          && f.type.items != null
          && "ref".equals(f.type.items.kind)) {
        b.append("    if (").append(field).append(" != null) {\n");
        b.append("      for (int i = 0; i < ").append(field).append(".size(); i++) {\n        ");
        b.append(field).append(".get(i).validate(").append(pointer).append(" + \"/\" + i);\n");
        b.append("      }\n    }\n");
      }
    }
    b.append("  }\n\n");
  }

  /** One {@code throw AuthZENRefusedException.of(...)}, laid out the way the formatter would. */
  private static String refusal(String code, String pointer, String message) {
    return Layout.call(
        "      ",
        "throw AuthZENRefusedException.of(",
        Arrays.asList("AuthZENErrorCode." + code, pointer, message),
        ");");
  }

  // -------------------------------------------------------------------------
  // Types and names
  // -------------------------------------------------------------------------

  private static void collectImports(TypeRef tr, Set<String> needed) {
    if (tr == null) {
      return;
    }
    if ("array".equals(tr.kind)) {
      needed.add("java.util.List");
      collectImports(tr.items, needed);
    } else if ("map".equals(tr.kind)) {
      needed.add("java.util.Map");
      collectImports(tr.value, needed);
    }
  }

  private static boolean isCollectionish(TypeRef tr) {
    return "array".equals(tr.kind) || "map".equals(tr.kind) || "object".equals(tr.kind);
  }

  private static String initialiser(FieldDecl f) {
    // An attribute bag is never null. An empty bag IS "the caller supplied no
    // attributes", and a null one would add a fourth state to a member whose
    // values already carry three.
    return "object".equals(f.type.kind) ? "new AttributeMap()" : "";
  }

  private static String javaType(FieldDecl f) {
    return javaType(f.type, f.required);
  }

  private static String javaType(TypeRef tr, boolean required) {
    switch (tr.kind) {
      case "string":
        return "String";
      case "bool":
      case "int":
        // ALWAYS boxed, required or not.
        //
        // A primitive for a required member reads as "absent is not a state the
        // contract allows", and that is true of the CONTRACT and false of the
        // decoder. Jackson leaves a missing primitive at its default, so an
        // omitted `obligation.mandatory` decoded to `false`, passed validation
        // (a primitive cannot be null, so there is nothing to check), and
        // `AuthZENDecision.getMandatoryObligations()` returned empty - turning
        // off the one instruction the caller must not ignore, silently. The
        // strict reader cannot help: it catches EXTRA members, never missing
        // ones.
        //
        // Boxed, the missing member is null and the generated validator refuses
        // it by name.
        return "bool".equals(tr.kind) ? "Boolean" : "Integer";
      case "object":
        return "AttributeMap";
      case "enum":
        return typeName(tr.enumName);
      case "ref":
        return typeName(tr.ref);
      case "array":
        return "List<" + javaType(tr.items, true) + ">";
      case "map":
        return "Map<String, " + javaType(tr.value, true) + ">";
      default:
        // Never a default type. An unrecognised kind silently rendered as
        // Object would compile, ship, and accept values the server refuses.
        throw new SurfaceException("unsupported type kind \"" + tr.kind + "\"");
    }
  }

  /**
   * Maps an artifact name onto this SDK's exported name.
   *
   * <p>{@code AuthZEN}, not {@code AuthZen}: these class names are matched LITERALLY against the
   * OpenAPI schema names by {@code scripts/wire_shape/validate.py}, and the specs spell them {@code
   * AuthZENSubject}. A prettier local spelling would make every one of these an unmatched
   * "SDK-only" class, which is exactly the coverage gap that gate exists to report.
   *
   * <p>Every generated type carries the prefix, not only the ones that would collide today. That
   * keeps the rule mechanical: a future collision does not require choosing a new convention under
   * time pressure.
   */
  private static String typeName(String artifactName) {
    String stripped =
        artifactName.startsWith("authzen_")
            ? artifactName.substring("authzen_".length())
            : artifactName;
    return "AuthZEN" + pascal(stripped);
  }

  private static String fieldName(String wire) {
    String camel = camel(wire);
    return isJavaKeyword(camel) ? camel + "Value" : camel;
  }

  private static String constantName(String wireValue) {
    StringBuilder b = new StringBuilder();
    for (String part : wireValue.split("[_.\\-]")) {
      if (part.isEmpty()) {
        continue;
      }
      if (b.length() > 0) {
        b.append('_');
      }
      b.append(part.toUpperCase());
    }
    return b.toString();
  }

  private static String camel(String s) {
    String[] parts = s.split("[_.\\-]");
    StringBuilder b = new StringBuilder();
    for (int i = 0; i < parts.length; i++) {
      if (parts[i].isEmpty()) {
        continue;
      }
      b.append(i == 0 ? parts[i] : upperFirst(parts[i]));
    }
    return b.toString();
  }

  private static String pascal(String s) {
    StringBuilder b = new StringBuilder();
    for (String part : s.split("[_.\\-]")) {
      if (!part.isEmpty()) {
        b.append(upperFirst(part));
      }
    }
    return b.toString();
  }

  private static String upperFirst(String s) {
    return Character.toUpperCase(s.charAt(0)) + s.substring(1);
  }

  private static boolean isJavaKeyword(String s) {
    return Arrays.asList(
            "abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class",
            "const", "continue", "default", "do", "double", "else", "enum", "extends", "final",
            "finally", "float", "for", "goto", "if", "implements", "import", "instanceof", "int",
            "interface", "long", "native", "new", "package", "private", "protected", "public",
            "return", "short", "static", "strictfp", "super", "switch", "synchronized", "this",
            "throw", "throws", "transient", "try", "void", "volatile", "while")
        .contains(s);
  }
}
